/* test_peer_discovery.c -- 2.3's peer discovery: what a node is TOLD about its
 * mesh, and what it is allowed to DO with it.
 *
 * docs/SERVER_DESIGN.md 2.3 ("Peer discovery and auto-scale stay Phase 9"), 8
 * ("peers and their FSM states must be dumpable") and the Phase 9 item this
 * test is the acceptance for: ADVERTISE, and a SHUTDOWN that is a goodbye rather
 * than a failure.
 *
 * This file replaces a ten-line placeholder in tests/loadbal/ that returned 77
 * and said "load-balancer peer discovery is not implemented". The CTest name is
 * unchanged (`PeerDiscovery`) -- see irc_ctest_name() in
 * tests/integration/CMakeLists.txt for why a moved test must not be renamed, and
 * tests/known_skips.txt for the ratchet that enforces it.
 *
 * ---------------------------------------------------------------------------
 * FOUR CLAIMS, AND WHERE EACH ONE IS ASSERTED
 * ---------------------------------------------------------------------------
 *   1. AN ADVERTISED DIAL HINT IS NEVER DIalled. server_t::advs is a store a peer
 *      writes and only a log reads; this is the SSRF claim, and it is asserted
 *      on the THIRD NODE rather than on a log line (see the next block).
 *   2. A CLEAN LEAVE IS NOT A FAILURE. fed_shutdown: ... retried=0, and -- the
 *      half with teeth -- the count of link_dial: lines on the departing link.
 *   3. AN ADVERTISE REQUIRES AN ESTABLISHED LINK. fed_preauth_drop:
 *      ... command=ADVERTISE state=PENDING, counted in fed_preauth_drop=.
 *   4. THE LOAD FIGURE PROPAGATES, in BOTH directions: what a peer sends is
 *      observed here (fed_advertise: ... load=37%), and what this node sends is
 *      read off this test's own socket (ADVERTISE 0). The outbound half is a ZERO
 *      and says why -- see LOAD_OUT_TEXT, which is the honest reading of a knob
 *      this build cannot turn.
 *
 * ---------------------------------------------------------------------------
 * WHY CLAIM 1 NEEDS A THIRD NODE, AND WHY TWO NODES COULD NOT CARRY IT
 * ---------------------------------------------------------------------------
 * The obvious two-node version is: peer irc.b advertises a name and an address,
 * and the test checks that node irc.a did not dial. That test is VACUOUS, and it
 * is vacuous for a structural reason rather than a subtle one. A two-node mesh
 * has exactly one address in it -- the one the two nodes are talking on -- so an
 * advertisement that "points somewhere else" has nowhere else to point, and the
 * only thing the observer could check is its own log. A log line is the GUARD
 * TALKING ABOUT ITSELF; a guard that printed `dialed=NO` and then dialled anyway
 * would sail past it. The same trap closed three times in this project already
 * (tests/integration/test_nick_duplicate.c documents the fourth instance, where a
 * two-node fixture could not tell "the server you named is not the holder" from
 * "the server you named is not a peer I can reach"), so the shape here is fixed:
 *
 *   irc.a   the node under test. It has EXACTLY ONE configured peer, irc.b.
 *   irc.b   THIS TEST, on a socket the test owns, so the payload is exact.
 *   irc.c   a real node with NO peers at all, and the target of the hint.
 *
 * irc.c is what makes the claim falsifiable. It is a listening node on a real
 * ephemeral port, so if the learned name ever reached the dial path the kernel
 * would complete a connection and irc.c would print `client_connect:` and
 * accepted=1. It has no peers, so `link_established:` on it is unambiguously
 * somebody dialling it out of nothing. And irc.a's own link set has no entry for
 * irc.c, so "the hint named something this node is not configured with" is a
 * statement about the link table rather than about a guess.
 *
 * ---------------------------------------------------------------------------
 * WHY THE PEER IS A RAW SOCKET (this file's irc.b) RATHER THAN A SECOND NODE
 * ---------------------------------------------------------------------------
 * Because a second node built from THIS code cannot produce the payloads the
 * claims are about. A real node's ADVERTISE is generated by fed_send_advertise()
 * from its own configuration, so it can only ever advertise a name and address
 * the operator gave it; it cannot be made to advertise irc.c at irc.c's port.
 * The same is true of SHUTDOWN: no node in this build ORIGINATES one at all
 * (fed_send_shutdown() has no caller -- server_shutdown() does not call it, so a
 * SIGTERM'd node says nothing and its peers time it out), which means the only
 * way to put a SHUTDOWN on a wire in a test is to write one. tests/integration/
 * test_fed_guards.c owns one end of a link for exactly the same reason and says
 * so at length; this file is the same technique applied to the two verbs of 2.3
 * rather than to the guard chain.
 *
 * What is NOT faked: the handshake is a real FEDERATE with the right name, the
 * right secret and the right version word, A's link goes through the real FSM,
 * and every line carries a 2.4 block produced by the node's own serialiser so
 * the guard chain above G10 is exercised rather than bypassed.
 *
 * ---------------------------------------------------------------------------
 * NO FIXED sleep() ANYWHERE (6.3)
 * ---------------------------------------------------------------------------
 * Every wait is a deadline: nf_expect()/nf_expect_u64() over a child's output,
 * or poll() with a deadline over this test's own socket. That is not only a style
 * rule here -- the claims are about TIMING (a retry that must not happen, a dial
 * that must not happen), so a test that slept a fixed second would be asserting
 * against a duration rather than against the node's behaviour.
 *
 * ---------------------------------------------------------------------------
 * THE TWO CLOCKS, AND WHY THEY ARE THE NODE'S AND NOT THIS TEST'S
 * ---------------------------------------------------------------------------
 * Two claims are absences, and an absence needs a window, and the window must be
 * the node's own clock rather than how fast this test can issue commands:
 *
 *   CLAIM 1's window is irc.a's T3 KEEPALIVE, shortened per process to 80 ms by
 *   fed_set_timeouts(). The test then reads N of those PINGs off its own socket.
 *   Each one is a tick of irc.a's, so N of them is N x 80 ms of irc.a running
 *   with the hint in its store -- and a keepalive is the cheapest line this tree
 *   can put on a peer link.
 *
 *   CLAIM 2's window is irc.d's T3 KEEPALIVE at 60 ms. irc.d's PINGs arrive at
 *   irc.a as INBOUND lines, so `lines=` on irc.a climbs on a real timer, and
 *   nf_expect_u64_ge(&a, "lines=", ...) is a deadline wait over that timer.
 *
 * AND THE BOUNDARY IS FAULT-INDEPENDENT IN BOTH CASES, which is the property that
 * makes the two windows worth having rather than decorative. Case 1's boundary is
 * irc.d's CLIENT lines -- inbound, and something a dial never produces -- and case
 * 2's is irc.d's keepalives, which likewise arrive as inbound lines. A boundary
 * measured on the very thing being asserted (irc.a's `accepted=`, or its
 * `link_dial:` count) would be satisfied BY the fault and would stop before it.
 *
 * The two other numbers that are shortened are named where they are set, with the
 * reason. What is NOT shortened anywhere: the ORDER of the guard chain, the
 * contents of the advertisement store, the shape of the retry ladder (base
 * doubled, capped, bounded by a budget that reports), and the single T7 condition
 * that refuses a diallable link. Those are the claims.
 */
#include <errno.h>
#include <netinet/in.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>

#include "core/commands.h"
#include "core/message.h"
#include "core/server.h"
#include "federation/link.h"
#include "harness/irc_client.h"
#include "harness/node_fixture.h"
#include "harness/test_util.h"

#define T_IO_MS 15000

#define SECRET "irc-serve-peer-discovery-secret"
#define NAME_A "irc.a" /* the node under test in both cases        */
#define NAME_B "irc.b" /* the name this test's socket claims       */
#define NAME_C "irc.c" /* the third node: a hint's target          */
#define NAME_D "irc.d" /* the keepalive clock in the clean-leave case */

/* THE LOAD FIGURES, AND THE HONEST ASYMMETRY BETWEEN THE TWO DIRECTIONS.
 *
 * INBOUND is 37, and it is the real claim: a peer publishes a figure and this
 * node reports it back on its own `fed_advertise:` line. Nothing about it is a
 * default and nothing about it is a zero.
 *
 * OUTBOUND is 0, AND IT IS 0 BECAUSE THAT IS WHAT THIS BUILD DOES. link.h:846
 * declares fed_set_load() as the source of the figure and explains at length that
 * it is "an operator's value, not a measurement"; there is NO DEFINITION of it in
 * this tree (nm on libirc_core.a finds no such symbol, and a call to it fails to
 * link), so server_t::load_pct keeps the zero server_init() gave it and 0% is the
 * only figure this node is able to put on a wire. The case asserts 0% and says so
 * rather than asserting a figure the build cannot produce -- a needle for a
 * knob value nothing can set is a needle that matches nothing, and a wait for a
 * line that is never sent is a timeout that reports itself as a pass. */
#define LOAD_OUT_TEXT "0"
#define LOAD_IN_TEXT  "37"

/* The loopback address the hint names, in the NUMERIC form fed_send_advertise()
 * itself publishes (advert_peer_hint() renders inet_ntop output and this node
 * has no reverse lookup). */
#define HINT_HOST "127.0.0.1"

/* irc.a's keepalive in the SSRF case, and the window multiplier. 80 ms is two
 * POLL_TICK_MS, so it is the shortest interval at which a keepalive is not
 * racing its own tick; six of them is 480 ms, which is nine times the 50 ms a
 * dial of an in-process address takes. The value is a TEST value and says
 * nothing about how the shipped 30 s interval behaves in the field -- what the
 * shortened number preserves is that the arm is on a clock at all. */
#define KA_FAST_MS 80
#define WINDOW_PINGS 6

/* The clean-leave case's ladder and its window, and the four numbers are ONE
 * calculation rather than four choices.
 *
 * IRC_FED_RETRY_BASE_MS ships at IRC_FED_DEAD_MS (90 s), so the first rung of an
 * unsuppressed redial would be a minute and a half after the socket closed and a
 * test that waited for one would not finish. 60 ms with a 240 ms ceiling keeps
 * the ladder's SHAPE (base x 2^attempt, capped, budget 3, exhaustion reported)
 * and changes only its scale, which is the trade federation/link.h's
 * fed_set_retry() paragraph exists to make.
 *
 * WITH irc.a's dead threshold at 150 ms (DEAD_MS below), an unsuppressed clean
 * leave would be re-dialled at
 *
 *      150 +  60 = 210 ms     first rung
 *      210 + 120 = 330 ms     second
 *      330 + 240 = 570 ms     third, at the ceiling
 *      570 + 240 = 810 ms     fourth -- and the budget is 3, so this one does not
 *                             happen; irc.a would print link_retry_exhausted:
 *
 * and the observation window is " WINDOW_LINES " of irc.d's 60 ms keepalives,
 * which is 960 ms. So the window is past EVERY rung including the budget's last,
 * by 150 ms, and the assertion is made over a span in which an unsuppressed leave
 * would have dialled three times. This margin is not decoration: the first
 * version of these numbers put the first rung at 420 ms and the window at
 * 800 ms, which sounds generous and was not, because `base` is read before the
 * SHUTDOWN and the inbound lines that open the window start arriving before it.
 * The teeth run found the fault un-caught 3 times out of 3, and the cause was
 * that margin, not the assertion. */
#define RETRY_BASE_MS 60
#define RETRY_MAX_MS  240
#define WINDOW_LINES  16

/* irc.a's dead threshold in the clean-leave case. Short so T4 declares the
 * departed peer dead quickly; the retry ladder above is scaled to match it so the
 * first rung is 210 ms after the socket closes. This is the one link timer
 * fed_set_timeouts() takes separately precisely so a case can declare a liveness
 * threshold on its own terms. */
#define DEAD_MS 150

/* ---------------------------------------------------------------------------
 * The child
 * ---------------------------------------------------------------------------
 * One setup for every node in the file, driven by a global the parent fills in
 * before each spawn. `load_pct` is a knob rather than a measurement: this node
 * measures no load, so the only honest figure on the wire is one somebody set.
 */
typedef struct {
    const char *name; /* NULL: no peer at this slot */
    int         port;
} peer_cfg_t;

typedef struct {
    peer_cfg_t peers[2];
    uint64_t   dial_ms;
    uint64_t   hs_ms;
    uint64_t   keepalive_ms;
    uint64_t   dead_ms;
    uint64_t   retry_base_ms;
    uint64_t   retry_max_ms;
    unsigned   retry_budget;
} child_cfg_t;

static child_cfg_t g_cfg;

static void child_setup(server_t *s)
{
    /* The client command surface, installed BEFORE fed_open(): fed_open() saves
     * whatever dispatch is there and installs its own over it, so a
     * commands_dispatch installed afterwards would become the node's whole
     * dispatch and the peer path would never be reached -- the client dispatch
     * is what routes a CONN_SERVER connection into fed_dispatch(). */
    s->dispatch = commands_dispatch;

    TF_CHECK_MSG(fed_open(s, SECRET) == 0,
                 "fed_open() failed in the child; a node with an unopenable "
                 "federation module cannot reach any assertion in this test");
    s->on_tick = fed_tick;

    /* A 0 argument keeps the built-in, so this is safe to call unconditionally
     * and a node that wants the shipped values says nothing. */
    fed_set_timeouts(g_cfg.dial_ms, g_cfg.hs_ms, g_cfg.keepalive_ms, g_cfg.dead_ms);
    /* NO fed_set_load() CALL, and the omission is deliberate: the function is
     * declared and never defined, so a call here would not link. The consequence
     * for this file is that the figure this node publishes is the zero
     * server_init() left behind -- see LOAD_OUT_TEXT. */
    if (g_cfg.retry_base_ms != 0u) {
        fed_set_retry(g_cfg.retry_base_ms, g_cfg.retry_max_ms, g_cfg.retry_budget);
    }
    for (size_t i = 0; i < sizeof g_cfg.peers / sizeof g_cfg.peers[0]; i++) {
        struct sockaddr_in sa;

        if (g_cfg.peers[i].name == NULL) {
            continue;
        }
        memset(&sa, 0, sizeof sa);
        sa.sin_family = AF_INET;
        sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        sa.sin_port = htons((unsigned short)g_cfg.peers[i].port);
        TF_CHECK_MSG(fed_link_configure(s, g_cfg.peers[i].name,
                                        (const struct sockaddr *)&sa,
                                        (socklen_t)sizeof sa) != NULL,
                     "the child could not configure peer %s on port %d",
                     g_cfg.peers[i].name, g_cfg.peers[i].port);
    }
}

/* ---------------------------------------------------------------------------
 * The test's end of a peer link
 * ---------------------------------------------------------------------------
 * A buffer that PERSISTS across calls, which is why this is a struct rather than
 * the local buffer test_fed_guards.c's read_until() uses: one call here consumes
 * the bytes it read, and the next call has to be able to see the ones after them
 * without seeing the ones before.
 */
typedef struct {
    int    fd;
    char   seen[16384];
    size_t used;
} peer_t;

static uint64_t now_ms(void)
{
    struct timespec ts;

    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
        return 0;
    }
    return (uint64_t)ts.tv_sec * 1000u + (uint64_t)(ts.tv_nsec / 1000000L);
}

static int listen_loopback(int *port_out)
{
    struct sockaddr_in sa;
    socklen_t len = sizeof sa;
    int one = 1;
    int fd = socket(AF_INET, SOCK_STREAM, 0);

    if (fd < 0) {
        return -1;
    }
    (void)setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);
    memset(&sa, 0, sizeof sa);
    sa.sin_family = AF_INET;
    sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    sa.sin_port = 0;
    if (bind(fd, (struct sockaddr *)&sa, sizeof sa) != 0 ||
        listen(fd, 8) != 0 ||
        getsockname(fd, (struct sockaddr *)&sa, &len) != 0) {
        close(fd);
        return -1;
    }
    *port_out = (int)ntohs(sa.sin_port);
    return fd;
}

static int accept_deadline(int listen_fd, int timeout_ms)
{
    uint64_t deadline = now_ms() + (uint64_t)timeout_ms;

    for (;;) {
        struct pollfd pfd;
        uint64_t left = (deadline > now_ms()) ? deadline - now_ms() : 0;
        int rc;

        pfd.fd = listen_fd;
        pfd.events = POLLIN;
        pfd.revents = 0;
        rc = poll(&pfd, 1, (int)left);
        if (rc < 0) {
            if (errno == EINTR) {
                continue;
            }
            return -1;
        }
        if (rc == 0) {
            return -1;
        }
        return accept(listen_fd, NULL, NULL);
    }
}

static int send_line(int fd, const char *line)
{
    size_t n = strlen(line);
    size_t off = 0;

    while (off < n) {
        ssize_t got = write(fd, line + off, n - off);

        if (got <= 0) {
            if (got < 0 && errno == EINTR) {
                continue;
            }
            return -1;
        }
        off += (size_t)got;
    }
    return 0;
}

/* Read whatever has arrived, up to the deadline. Returns 0 if it read anything,
 * -1 on a closed socket, and 1 if the deadline passed with nothing new. */
static int peer_fill(peer_t *p, int timeout_ms)
{
    uint64_t deadline = now_ms() + (uint64_t)timeout_ms;

    for (;;) {
        struct pollfd pfd;
        uint64_t left = (deadline > now_ms()) ? deadline - now_ms() : 0;
        ssize_t got;
        size_t room;
        int rc;

        pfd.fd = p->fd;
        pfd.events = POLLIN;
        pfd.revents = 0;
        rc = poll(&pfd, 1, (int)left);
        if (rc < 0) {
            if (errno == EINTR) {
                continue;
            }
            return -1;
        }
        if (rc == 0) {
            return 1;
        }
        room = sizeof p->seen - 1u - p->used;
        if (room == 0u) {
            return 1;
        }
        got = read(p->fd, p->seen + p->used, room);
        if (got == 0) {
            return -1;
        }
        if (got < 0) {
            if (errno == EINTR) {
                continue;
            }
            return -1;
        }
        p->used += (size_t)got;
        p->seen[p->used] = '\0';
        return 0;
    }
}

/* How many times `needle` has arrived, counted non-overlapping. */
static size_t peer_count(const peer_t *p, const char *needle)
{
    size_t nlen = strlen(needle);
    size_t seen = 0u;

    for (const char *at = p->seen; (at = strstr(at, needle)) != NULL; at += nlen) {
        seen++;
    }
    return seen;
}

/* Read until `needle` has arrived, or the deadline passes.
 *
 * THE BUFFER IS SEARCHED BEFORE THE SOCKET IS READ, and that ordering is the
 * whole of this function rather than a style choice. A peer that has closed its
 * end reports POLLIN|POLLHUP, read() answers 0, and a fill-first loop returns
 * "closed" without ever looking at the bytes already sitting in the buffer -- so
 * the last line a peer ever sent is exactly the one this could miss. It is the
 * same reason harness/node_fixture.h's nf_expect() searches the accumulated
 * buffer: what has arrived is a fact, and a later event does not un-arrive it. */
static int peer_expect(peer_t *p, const char *needle, int timeout_ms)
{
    uint64_t deadline = now_ms() + (uint64_t)timeout_ms;

    for (;;) {
        int rc;

        if (strstr(p->seen, needle) != NULL) {
            return 0;
        }
        rc = peer_fill(p, timeout_ms);
        if (rc < 0) {
            return (strstr(p->seen, needle) != NULL) ? 0 : -1;
        }
        if (now_ms() >= deadline) {
            return -1;
        }
        timeout_ms = 1;
    }
}

/* Read until `needle` has arrived at least `want` TIMES, or the deadline passes.
 *
 * The COUNT is the point. A single line of irc.a's (one keepalive) is one tick of
 * irc.a's, and six of them are a window of irc.a's own making -- which is what an
 * absence claim has to be measured over. A test that instead waited a fixed
 * number of milliseconds would be measuring this process's clock and asserting
 * nothing about the node's. Searched before the read, for the reason above. */
static int peer_expect_n(peer_t *p, const char *needle, size_t want, int timeout_ms)
{
    uint64_t deadline = now_ms() + (uint64_t)timeout_ms;

    for (;;) {
        int rc;

        if (peer_count(p, needle) >= want) {
            return 0;
        }
        rc = peer_fill(p, timeout_ms);
        if (rc < 0) {
            return (peer_count(p, needle) >= want) ? 0 : -1;
        }
        if (now_ms() >= deadline) {
            return -1;
        }
        timeout_ms = 1;
    }
}

/* The peer's 2.4 id stream. Handed out by this test rather than by a counter in
 * link.c because this socket is a peer: two of its lines must not collide in
 * irc.a's dedup store, or the second would be dropped as a duplicate and a case
 * would be measuring G7 instead of the verb. */
static uint64_t g_stamp_id = 1;

/* Send one stamped peer line: `@<block> :" NAME_B <verb> <tail>`. The block comes
 * from the node's OWN serialiser, which is the right choice here and the wrong
 * one in test_fed_tags.c: that file asserts the serialiser, so it spells the block
 * out literally. This file asserts what the guard chain does with a well-formed
 * line, so it wants the line a peer of this build would actually send. */
static void peer_send(peer_t *p, const char *verb, const char *tail)
{
    irc_serve_tags_t t;
    char block[IRC_MAX_TAG_OVERHEAD];
    char line[IRC_MAX_LINE];
    uint64_t id = g_stamp_id++;
    size_t blen;

    memset(&t, 0, sizeof t);
    memcpy(t.origin, NAME_B, strlen(NAME_B) + 1u);
    t.epoch = 1700000000u;
    t.id = id;
    t.hops = 1;
    blen = irc_serve_tags_format(&t, block, sizeof block);
    TF_CHECK_MSG(blen != 0u,
                 "the test could not serialise a 2.4 stamp, so every line it "
                 "sends would be refused before the verb under test was read");
    (void)snprintf(line, sizeof line, "@%s :" NAME_B " %s %s\r\n", block, verb, tail);
    TF_CHECK_MSG(send_line(p->fd, line) == 0, "the test could not send a %s", verb);
}

/* irc.a's claim, read before this test answers it. "A established a link" would
 * otherwise be satisfied by a node that never said hello. Pinned on both sides of
 * the epoch, which is a clock reading on irc.a's side. */
static void peer_expect_claim(peer_t *p)
{
    const char *const needles[] = {
        ":" NAME_A " FEDERATE " NAME_A " ",
        " " SECRET " " IRC_SERVE_VERSION "\r\n"
    };

    TF_CHECK_MSG(peer_expect(p, needles[0], T_IO_MS) == 0,
                 "irc.a never named itself in a FEDERATE, so nothing after this "
                 "could mean anything. What arrived on this socket: %s",
                 p->seen);
    TF_CHECK_MSG(peer_expect(p, needles[1], T_IO_MS) == 0,
                 "irc.a's claim did not carry the configured secret and the "
                 "version word, so the handshake below would be refused for a "
                 "reason that has nothing to do with the verbs under test. What "
                 "arrived on this socket: %s",
                 p->seen);
}

/* The answer. A genuine claim in every field, so the handshake SUCCEEDS and the
 * handlers below are reachable at all. */
static void peer_answer_claim(peer_t *p)
{
    char line[512];

    (void)snprintf(line, sizeof line, ":" NAME_B " FEDERATE " NAME_B " 1700000000 "
                                         SECRET " " IRC_SERVE_VERSION "\r\n");
    TF_CHECK_MSG(send_line(p->fd, line) == 0,
                 "the test could not answer irc.a with a FEDERATE");
}

/* Register a client on `port` and drain it with a UNIQUE token, so every later
 * wait on this connection is against bytes read since. tc_expect() searches the
 * whole accumulated buffer, so a shared token would let one drain satisfy the
 * next. The client is here to be a CLOCK and a PUMP, not to observe anything --
 * see the comment at the assertion that reads irc.c's counters. */
static void register_client(test_client_t *c, int port, const char *nick,
                            const char *token)
{
    char line[256];

    TF_CHECK_MSG(tc_connect(c, port) == 0, "%s could not connect", nick);
    (void)snprintf(line, sizeof line, "NICK %s", nick);
    TF_CHECK_MSG(tc_send(c, line) == 0, "NICK send failed for %s", nick);
    (void)snprintf(line, sizeof line, "USER %s 0 *spoofed :Real %s", nick, nick);
    TF_CHECK_MSG(tc_send(c, line) == 0, "USER send failed for %s", nick);
    TF_CHECK_MSG(tc_expect(c, " 001 ", T_IO_MS) == 0, "%s never registered", nick);
    (void)snprintf(line, sizeof line, "PING :%s", token);
    TF_CHECK_MSG(tc_send(c, line) == 0, "%s's drain PING send failed", nick);
    TF_CHECK_MSG(tc_expect(c, token, T_IO_MS) == 0,
                 "%s got no PONG carrying its drain token, so the lines before it "
                 "have not been read yet",
                 nick);
}

/* ---------------------------------------------------------------------------
 * CASE 1 -- CLAIMS 3, 4 AND 1, ON ONE LINK
 * ---------------------------------------------------------------------------
 * irc.a dials this test. The order of the beats is the argument:
 *
 *   1. a HINT BEFORE THE HANDSHAKE. The exact payload that will be accepted in
 *      beat 3 is sent first, and refused -- so the refusal in beat 1 is about the
 *      LINK and not about the payload, which beat 3 then proves by accepting it.
 *   2. the handshake, which also proves the drop did not tear the link down.
 *   3. the load figure, with no hint: what a peer publishes about itself.
 *   4. irc.a's own figure, read off this socket: the SEND direction, on the wire.
 *   5. the HINT, post-handshake, naming irc.c at irc.c's port.
 *   6. irc.a's clock for 480 ms, and irc.c's silence for all of it.
 */
static void case_a_hint_is_recorded_and_never_dialled(void)
{
    nf_node_t a;
    nf_node_t c;
    peer_t p;
    test_client_t probe;
    int listen_fd;
    int b_port = 0;
    char hint[128];
    char needle[256];
    uint64_t c_accepted = 0;

    /* THE TEST'S OWN LISTENER IS OPENED FIRST, because it is irc.a's only peer
     * and irc.a is spawned against its port. */
    listen_fd = listen_loopback(&b_port);
    TF_CHECK_MSG(listen_fd >= 0, "the test could not open a listening socket");

    memset(&g_cfg, 0, sizeof g_cfg);
    g_cfg.peers[0].name = NAME_B;
    g_cfg.peers[0].port = b_port;
    g_cfg.dial_ms = 1000;
    g_cfg.hs_ms = 5000;
    /* THE KEEPALIVE IS THE CLOCK (see the file header) and the DEAD THRESHOLD IS
     * NOT. irc.a's only peer is a socket this test owns, and this test does not
     * answer irc.a's keepalives, so a short dead threshold would have T4 declare
     * the link dead a few hundred ms into the case and take the link under the
     * later beats. 90 s is IRC_FED_DEAD_MS against the shipped keepalive, so the
     * only thing shortened here is the interval this test reads a clock from. */
    g_cfg.keepalive_ms = KA_FAST_MS;
    g_cfg.dead_ms = 3u * 30000u;
    TF_CHECK_MSG(nf_spawn_inline_named(&a, NAME_A, child_setup) == 0,
                 "could not spawn node " NAME_A);

    /* irc.c: a real node, on a real port, with NO PEERS. It exists so that
     * "nothing happened" is a statement about a listening node rather than about
     * this test's imagination. It has no peer of its own, so a link_established
     * on it could only have come from somebody dialling a name it was told. */
    memset(&g_cfg, 0, sizeof g_cfg);
    TF_CHECK_MSG(nf_spawn_inline_named(&c, NAME_C, child_setup) == 0,
                 "could not spawn node " NAME_C);
    TF_CHECK_MSG(c.port > 0, "node " NAME_C " reported no port, so a hint could "
                             "not name an address that would really accept a "
                             "connection");

    (void)snprintf(hint, sizeof hint, LOAD_IN_TEXT " " NAME_C " " HINT_HOST " %d",
                   c.port);
    (void)snprintf(needle, sizeof needle,
                   "fed_advertise: peer=" NAME_B " name=" NAME_C " host=" HINT_HOST
                   " port=%d load=" LOAD_IN_TEXT "%% dialed=NO",
                   c.port);

    p.fd = accept_deadline(listen_fd, T_IO_MS);
    /* Closed here and not at the end: this listener is irc.a's only peer and a
     * second accept would be a second link, which is not the fixture. */
    close(listen_fd);
    TF_CHECK_MSG(p.fd >= 0, "irc.a never dialled the socket this test owns");
    p.used = 0u;
    p.seen[0] = '\0';

    peer_expect_claim(&p);

    /* --- beat 1: the HINT BEFORE THE HANDSHAKE ----------------------------- */
    /* The SAME payload beat 3 sends. Sending it here is what makes beat 1's
     * refusal mean something: a payload refused for its own sake would be refused
     * again in beat 3, and a test could not tell the two reasons apart. */
    peer_send(&p, "ADVERTISE", hint);

    /* The observable is G1's own line, and `state=PENDING` is the half of it that
     * names the cause: the link existed and was not ESTABLISHED. (The `NONE`
     * spelling is the other arm -- no link at all -- and this is not it.) */
    TF_CHECK_MSG(nf_expect(&a, "command=ADVERTISE state=PENDING", T_IO_MS) == 0,
                 "an ADVERTISE that arrived before the handshake completed was not "
                 "refused. It carries a dial hint, and a hint accepted from "
                 "anything that opened a TCP connection is a hint accepted from a "
                 "stranger: %s",
                 a.out);
    /* AND COUNTED, which is the half an operator reads. fed_preauth_drop= is not
     * one of the counters that drives the harness's republication, but the line
     * this drop counted ALSO arrived, so n_lines moved, so the stats line
     * carrying fed_preauth_drop=1 was printed -- which is what makes this wait
     * terminate rather than time out. */
    TF_CHECK_MSG(nf_expect_u64(&a, "fed_preauth_drop=", 1u, T_IO_MS) == 0,
                 "the pre-handshake ADVERTISE was refused but not counted, so a "
                 "node being spoken to by something that is not a peer is "
                 "invisible in the numbers: %s",
                 a.out);
    /* AND NOT RECORDED. One hint is refused by the LINK and one is accepted by
     * the store; if this one had been stored, the count below would be three and
     * the case would be claiming the store refused a payload it accepts. */
    TF_CHECK_MSG(tf_count(a.out, "fed_advertise: peer=") == 0u,
                 "an ADVERTISE from a link that is not ESTABLISHED reached the "
                 "advertisement store, so a stranger's dial hint was recorded "
                 "before the handshake that makes a stranger a peer: %s",
                 a.out);

    /* --- beat 2: the handshake, which is also the "not torn down" proof ---- */
    /* No separate assertion for "the drop did not close the socket". The very
     * next thing this test sends is the claim, and the link reaching ESTABLISHED
     * is that assertion: a guard that answered a stranger by closing would make a
     * peer that speaks before it says hello permanently unconnectable. */
    peer_answer_claim(&p);
    TF_CHECK_MSG(nf_expect(&a, "link_established: peer=" NAME_B, T_IO_MS) == 0,
                 "irc.a never established its link, so every beat after this is "
                 "unreachable and the case would be asserting against a node with "
                 "no peer at all: %s",
                 a.out);

    /* --- beat 3: the load figure a peer sent ------------------------------- */
    peer_send(&p, "ADVERTISE", LOAD_IN_TEXT);
    TF_CHECK_MSG(nf_expect(&a, "fed_advertise: peer=" NAME_B " load=" LOAD_IN_TEXT
                               "% dialed=NO",
                           T_IO_MS) == 0,
                 "a load figure published by a peer was not observed by irc.a. "
                 "The percentage is the only payload this node has to propagate "
                 "and it is REQUIRED rather than optional, so a figure that does "
                 "not propagate is a mesh that cannot see itself load: %s",
                 a.out);

    /* --- beat 4: irc.a's OWN figure, read off this socket ------------------ */
    /* The other direction, and the only assertion here that is about the SENDER.
     * It is on the wire rather than in a log because the claim is that the figure
     * reaches a peer, and a log line on the sending node would only say the node
     * believed it had sent something. The figure is " LOAD_OUT_TEXT " and NOT a
     * knob value: fed_set_load() is declared and never defined, so this node has
     * no way to be told anything else and 0% is what it can honestly publish. */
    TF_CHECK_MSG(peer_expect(&p, "ADVERTISE " LOAD_OUT_TEXT, T_IO_MS) == 0,
                 "irc.a never advertised its own load figure on this link. It is "
                 "sent once on establishment, so this wait covers the whole "
                 "claim: %s",
                 p.seen);

    /* --- beat 5: the HINT, post-handshake --------------------------------- */
    peer_send(&p, "ADVERTISE", hint);
    TF_CHECK_MSG(nf_expect(&a, needle, T_IO_MS) == 0,
                 "a dial hint naming " NAME_C " -- a server this node has no "
                 "configured peer for -- was not recorded and reported with "
                 "dialed=NO. The store has to REPORT it, because an operator "
                 "asking whether a peer is lying about its mesh can only answer "
                 "from a line like this one: %s",
                 a.out);
    /* ONE SLOT, REFRESHED. Three ADVERTISE lines arrived (one refused pre-
     * handshake, one bare, one with a hint) and the store holds one entry, keyed
     * on the LINK rather than on the advertised name -- so a peer cannot overwrite
     * another peer's entry by naming it. The count is the observable for that;
     * fed_advertised_count() would be a struct read. */
    TF_CHECK_MSG(tf_count(a.out, "fed_advertise: peer=" NAME_B) == 2u,
                 "irc.a reported %zu advertisements for peer " NAME_B ", expected "
                 "the two that were sent on an ESTABLISHED link and no third: %s",
                 tf_count(a.out, "fed_advertise: peer=" NAME_B), a.out);
    /* AND irc.a DIALLED EXACTLY ONCE, which is the corroborating half of claim 1
     * on irc.a's own side: the only peer in its link table is " NAME_B ", and the
     * only dial it ever started was the one that opened this socket. */
    TF_CHECK_MSG(tf_count(a.out, "link_dial: peer=" NAME_B) == 1u,
                 "irc.a started %zu dials to peer " NAME_B
                 ", so a learned name reached the dial path: %s",
                 tf_count(a.out, "link_dial: peer=" NAME_B), a.out);

    /* --- beat 6: irc.a's clock, irc.c's own clock, and irc.c's silence ------ */
    /* Six keepalives at " KA_FAST_MS " is irc.a's window. See peer_expect_n(): the
     * count is of lines irc.a SENT on a timer of its own, so the absence below is
     * measured over irc.a running with the hint in its store, not over this test
     * being slow. */
    TF_CHECK_MSG(peer_expect_n(&p, " PING ", (size_t)WINDOW_PINGS, T_IO_MS) == 0,
                 "irc.a sent %d keepalives in the observation window, so the "
                 "window never opened and the absence asserted below would be "
                 "vacuous. A dial of an in-process address completes in "
                 "microseconds and the arm is on a 50 ms tick, so a node that had "
                 "not finished deciding inside 480 ms was never going to: %s",
                 WINDOW_PINGS, p.seen);

    /* ONE REAL CLIENT ON irc.c, AND IT IS HERE TO BOUND AN ABSENCE RATHER THAN TO
     * OBSERVE ANYTHING. Without it the absence below is unsound, and the reason
     * is specific enough to be worth the twenty lines: nf_find_u64() and the
     * strstr()s read what the PARENT has already pumped off the child's stdout, and
     * one nf_expect() call performs at most one pump. So a node that accepted a
     * connection during the window and printed it would be invisible to a test
     * whose last read of that node happened before the window opened. This was
     * measured, not assumed: an injected fault that turned the hint into a
     * configured peer was caught in 4 runs out of 8 with a single pump, and in 8
     * out of 8 with the boundary below.
     *
     * THE BOUNDARY IS `lines=` AND THAT IS THE WHOLE POINT. A client line is an
     * INBOUND line, so it moves `lines=` on irc.c, and a dial that connects and
     * says nothing moves nothing. So waiting for a line count the CLIENT caused
     * puts the read strictly after the window AND strictly after anything a dial
     * printed during it -- a boundary no amount of stray connections can move
     * earlier. A boundary on `accepted=` would not do: a dial's own accept would
     * satisfy it. */
    register_client(&probe, c.port, "probe", "reg-probe");

    /* A SECOND ROUND TRIP, issued after the window, so the wait below is anchored
     * on work irc.c did because this test asked after the window had closed. */
    TF_CHECK_MSG(tc_send(&probe, "PING :after-window") == 0,
                 "the probe client's post-window PING send failed");
    TF_CHECK_MSG(tc_expect(&probe, "after-window", T_IO_MS) == 0,
                 "the probe client never got its post-window PONG, so irc.c had "
                 "not processed anything after the window and the read below "
                 "would be about bytes from before it: %s",
                 tc_buffer(&probe));
    /* Four is a LOWER BOUND, not a count: NICK, USER and the registration drain
     * are three, this PING is the fourth, and anything else the client surface
     * sends is welcome. */
    TF_CHECK_MSG(nf_expect_u64_ge(&c, "lines=", 4u, T_IO_MS) == 0,
                 "node " NAME_C " did not publish an inbound line count of at "
                 "least 4, so the pump that makes the absence below meaningful "
                 "never completed and a connection made during the window would be "
                 "invisible: %s",
                 c.out);

    /* THE ABSENCE, on the node the hint names, in four independent spellings.
     * They are four because they are four different failures:
     *   accepted=1 / one client_connect:  something dialled it
     *   link_established:                 it completed a handshake, so it was named
     *   no fed_advertise:                 it was itself told about a peer, which a
     *                                     node with no peers can only be by a link
     * Anything less than all four passes against a partial dial. */
    TF_CHECK_MSG(nf_find_u64(&c, "accepted=", &c_accepted) == 0 &&
                     c_accepted == 1u,
                 "node " NAME_C " accepted %llu connections and exactly one is "
                 "this test's own probe client. " NAME_C " has no configured peers "
                 "and nothing else ever connected to it, so the only thing that "
                 "could have dialled it is a name it learned: %s",
                 (unsigned long long)c_accepted, c.out);
    TF_CHECK_MSG(tf_count(c.out, "client_connect:") == 1u,
                 "node " NAME_C " logged %zu inbound connections and this test "
                 "made one, so something else reached its listener inside the "
                 "window in which " NAME_A " held a hint naming it: %s",
                 tf_count(c.out, "client_connect:"), c.out);
    TF_CHECK_MSG(strstr(c.out, "link_established:") == NULL,
                 "node " NAME_C " established a link. It has no configured peers, "
                 "so there was no honest way for that to happen: %s",
                 c.out);
    TF_CHECK_MSG(strstr(c.out, "fed_advertise") == NULL,
                 "node " NAME_C " received an ADVERTISE, so the hint did more "
                 "than produce a connection: %s",
                 c.out);

    TF_CHECK_MSG(nf_stop(&a) == 0, "node " NAME_A " did not exit cleanly");
    TF_CHECK_MSG(nf_stop(&c) == 0, "node " NAME_C " did not exit cleanly");
    close(p.fd);
    tc_close(&probe);
    nf_free(&a);
    nf_free(&c);
}

/* ---------------------------------------------------------------------------
 * CASE 2 -- CLAIM 2: A CLEAN LEAVE IS NOT A FAILURE
 * ---------------------------------------------------------------------------
 * THE FIXTURE IS THREE THINGS AND EACH IS LOAD-BEARING:
 *
 *   irc.a  dials irc.b, which is THIS TEST's socket. irc.a MUST BE THE INITIATOR,
 *           and that is not a detail: T7's arm is guarded by
 *           `link->initiator != 0 && link->addrlen != 0`, because an ACCEPTED link
 *           has no address and could never be dialled anyway. On the accepting
 *           side a clean-leave suppression is therefore untestable -- the redial
 *           would not happen with or without it -- so a test that let irc.a accept
 *           the link would pass against a node that had no suppression at all.
 *
 *   irc.b  this test, which writes the SHUTDOWN. No node in this build can send
 *           one: fed_send_shutdown() has no caller anywhere in src/ (see the file
 *           header), so a real peer here would only ever close a socket.
 *
 *   irc.d  a real node that DIALS irc.a and keeps a 100 ms keepalive. It exists
 *           to be a clock (see the file header) and it is also the mesh the
 *           departure must be told onward to: a two-node mesh has nobody to tell,
 *           which is the same reason tests/integration/test_fed_resync.c needs
 *           four nodes.
 *
 * irc.a's dead threshold is 300 ms so T4 declares the departed peer dead and arms
 * the ladder quickly, and its retry base is 120 ms so the FIRST rung is due
 * 420 ms after the socket closed. The observation window is 800 ms of irc.d's
 * keepalives, which is past the second rung (660 ms) with margin.
 */
static void case_clean_leave_is_not_a_failure(void)
{
    nf_node_t a;
    nf_node_t d;
    peer_t p;
    int listen_fd;
    int b_port = 0;
    uint64_t base = 0;
    uint64_t dials;
    uint64_t arms;

    listen_fd = listen_loopback(&b_port);
    TF_CHECK_MSG(listen_fd >= 0, "the test could not open a listening socket");

    memset(&g_cfg, 0, sizeof g_cfg);
    g_cfg.peers[0].name = NAME_B;
    g_cfg.peers[0].port = b_port;
    g_cfg.dial_ms = 1000;
    g_cfg.hs_ms = 5000;
    /* THE KEEPALIVE STAYS LONG so irc.a does not flood this test's socket; the
     * DEAD THRESHOLD IS SHORT so T4 fires within the window instead of at 90 s.
     * Splitting them is what fed_set_timeouts() takes dead_ms for. */
    g_cfg.keepalive_ms = 5000;
    g_cfg.dead_ms = DEAD_MS;
    g_cfg.retry_base_ms = RETRY_BASE_MS;
    g_cfg.retry_max_ms = RETRY_MAX_MS;
    g_cfg.retry_budget = 3;
    TF_CHECK_MSG(nf_spawn_inline_named(&a, NAME_A, child_setup) == 0,
                 "could not spawn node " NAME_A);

    memset(&g_cfg, 0, sizeof g_cfg);
    g_cfg.peers[0].name = NAME_A;
    /* irc.d DIALS irc.a: one direction per pair, or both ends dial and neither
     * accepts (federation/link.h names the limitation). */
    g_cfg.peers[0].port = a.port;
    g_cfg.dial_ms = 1000;
    g_cfg.hs_ms = 5000;
    /* irc.d's keepalive is the CLOCK this case's window is measured on: each
     * PING is an inbound line on irc.a, so `lines=` there climbs on a real timer
     * and nf_expect_u64_ge() over it is a deadline wait rather than a sleep. */
    g_cfg.keepalive_ms = 60;
    g_cfg.dead_ms = 3u * 30000u;
    TF_CHECK_MSG(nf_spawn_inline_named(&d, NAME_D, child_setup) == 0,
                 "could not spawn node " NAME_D);

    p.fd = accept_deadline(listen_fd, T_IO_MS);
    close(listen_fd);
    TF_CHECK_MSG(p.fd >= 0, "irc.a never dialled the socket this test owns");
    p.used = 0u;
    p.seen[0] = '\0';
    peer_expect_claim(&p);
    peer_answer_claim(&p);

    TF_CHECK_MSG(nf_expect(&a, "link_established: peer=" NAME_B, T_IO_MS) == 0,
                 "irc.a never established its link to " NAME_B ", so nothing below "
                 "could mean anything: %s",
                 a.out);
    TF_CHECK_MSG(nf_expect(&a, "link_established: peer=" NAME_D, T_IO_MS) == 0,
                 "irc.a never accepted a link from " NAME_D ", so the departure "
                 "below has nowhere to be told onward to: %s",
                 a.out);
    TF_CHECK_MSG(nf_expect(&d, "link_established: peer=" NAME_A, T_IO_MS) == 0,
                 NAME_D " never established its link to " NAME_A ": %s", d.out);

    /* The count this case's window is measured from, taken BEFORE the departure
     * so that the window below is anchored on the socket closing rather than on
     * some later event. */
    TF_CHECK_MSG(nf_find_u64(&a, "lines=", &base) == 0,
                 "irc.a never published its inbound line count, so the "
                 "observation window below has no lower bound to grow from: %s",
                 a.out);

    /* --- the goodbye ------------------------------------------------------- */
    peer_send(&p, "SHUTDOWN", ":planned-restart");

    /* THIS TEST DOES NOT CLOSE ITS END OF THE LINK, AND THE REASON IS A DEFECT
     * IN THE SHIPPED LOOP rather than a style choice -- so it is worth writing
     * down exactly, because a reader who closes the socket here will watch this
     * case fail and will not know why.
     *
     * core/poll_loop.c's conn_on_readable() handles the end of a stream like
     * this:
     *
     *     rc = conn_fill(c);
     *     if (rc == CONN_FILL_EOF) { ...; conn_mark_closing(c); return; }
     *     ...
     *     conn_readable(s, c);
     *
     * and connection.c's conn_fill() LOOPS: it recv()s, appends to c->rbuf, and
     * goes round again until recv() answers EAGAIN or 0. So a peer that writes
     * its last line and then closes -- or half-closes -- in the same breath gets
     * one conn_fill() call that buffers the line AND reports EOF, and the EOF arm
     * returns WITHOUT calling conn_readable(). The line sits in c->rbuf, is never
     * framed, is never dispatched, and is discarded when the reaper frees the
     * conn. The node's own counters say so: `n_lines` does not move, and
     * `parse_reject` and `frame_error` are both 0 -- it never became a line.
     *
     * THAT IS NOT A CORNER CASE FOR THIS VERB. A graceful leave is precisely
     * "send the line, then go", so the one sequence item 4 is about is the one
     * this defect eats. It is not this pass's job to fix core/poll_loop.c, and a
     * test that asserted the current behaviour would enshrine it, so this case
     * routes around it: the test keeps its end open, which leaves the node's
     * conn_fill() answering EAGAIN (so the SHUTDOWN is framed normally), and the
     * node closes its OWN side -- which fed_in_shutdown() does, by marking the
     * connection CLOSING rather than by closing a descriptor, because 3.4 makes
     * the reaper the only place an fd is closed. That is asserted immediately
     * below, so "the node hung up" is an observable and not an assumption.
     *
     * The fix, when it is made, is to frame what conn_fill() already buffered
     * before honouring the EOF. */
    {
        int rc = 0;

        while ((rc = peer_fill(&p, T_IO_MS)) == 0) {
            /* drain irc.a's own traffic; the node's close is what ends this */
        }
        /* rc < 0 is end of stream: the node closed the peer socket, which is the
         * third thing a SHUTDOWN has to do and the one a log line cannot prove --
         * "a peer that said it is leaving and then kept the socket open would be a
         * peer whose word and whose behaviour disagree, and this node has no way
         * to make the word true" (verbs.c). rc == 1 would be the deadline, i.e.
         * the node still holding the socket open. */
        TF_CHECK_MSG(rc < 0,
                     "the node kept the peer socket open after a SHUTDOWN, so a "
                     "peer that says it is leaving and stays is not "
                     "distinguishable from a peer that says it is leaving and "
                     "goes");
    }
    close(p.fd);

    /* THE DECISION, and it is first because the implementation puts it first:
     * a log reader has to see the decision before the consequences of it. */
    TF_CHECK_MSG(nf_expect(&a, "link_clean_leave: peer=" NAME_B
                                  " reason=PEER_SHUTDOWN",
                           T_IO_MS) == 0,
                 "a peer that said it was leaving did not mark the link as "
                 "cleanly departed, so nothing downstream could distinguish it "
                 "from a peer that died: %s",
                 a.out);
    /* THE ACCOUNT. `clean_leave=1 retried=0` is the log-level claim and it is the
     * WEAKER of the two assertions in this case -- a node can print a flag it did
     * not honour. The stronger one is the link_dial: count below, which is a
     * count of sockets this node actually opened. `relayed=1` is the third half
     * and it is why irc.d exists: a departure a mesh does not hear about leaves
     * every other node holding a roster for a server that is gone. */
    TF_CHECK_MSG(nf_expect(&a, "chans=0 purged=0 relayed=1 clean_leave=1 retried=0",
                           T_IO_MS) == 0,
                 "the SHUTDOWN was not accounted for as a clean, unretried, "
                 "forwarded departure. relayed=1 is the part with teeth: irc.d was "
                 "established and must have been told: %s",
                 a.out);
    /* AND TOLD ONWARD, on the node two hops from the event. A SQUIT and not a
     * relayed SHUTDOWN, because SQUIT is the verb the receiving side knows how to
     * act on; the observable here is the one a peer of an older build would also
     * produce. */
    TF_CHECK_MSG(nf_expect(&d, "fed_squit: server=" NAME_B, T_IO_MS) == 0,
                 "the departure of " NAME_B " never reached " NAME_D
                 ", so a node two hops away is still holding its roster: %s",
                 d.out);

    /* T4 firing at all is the honest counterweight to the claims above: the peer
     * DID go silent and the node DID treat that as a failure, so what is being
     * asserted is not "the node noticed nothing" but "the node noticed and then
     * declined to spend a retry on it". */
    TF_CHECK_MSG(nf_expect(&a, "link_dead: peer=" NAME_B, T_IO_MS) == 0,
                 "irc.a never declared the departed link dead, so the assertions "
                 "below would be passing because the node never noticed rather "
                 "than because it decided: %s",
                 a.out);

    /* --- the window -------------------------------------------------------- */
    /* " WINDOW_LINES " inbound lines at irc.d's 60 ms keepalive is 960 ms, read as
     * a deadline over a counter irc.a publishes. Past EVERY rung of the " RETRY_BASE_MS
     * " ms ladder and past the budget's last, so an unsuppressed clean leave
     * would have dialled three times inside it. The arithmetic is at
     * " WINDOW_LINES " and the margin is not decoration -- see the comment there. */
    TF_CHECK_MSG(nf_expect_u64_ge(&a, "lines=", base + (uint64_t)WINDOW_LINES,
                                  T_IO_MS) == 0,
                 "irc.a received %llu inbound lines and the observation window "
                 "never opened, so the absence below would be vacuous: %s",
                 (unsigned long long)base, a.out);

    /* THE ASSERTION WITH TEETH. Exactly one dial to " NAME_B " in irc.a's whole
     * life: the one that opened this socket. A retrying goodbye prints a second
     * link_dial: line inside this window and fails this, which is the failure the
     * case exists to catch -- a planned restart spent as three dials, two minutes
     * of backoff and a link in a dump that looks retryable. */
    dials = tf_count(a.out, "link_dial: peer=" NAME_B);
    TF_CHECK_MSG(dials == 1u,
                 "irc.a dialled peer " NAME_B " %llu times. It dialled it once to "
                 "open this link, and a peer that said SHUTDOWN must never be "
                 "dialled again without an operator resetting it: %s",
                 (unsigned long long)dials, a.out);
    /* AND THE LADDER WAS STILL ARMED, exactly once. This is what makes the count
     * above an assertion about the clean-leave guard rather than about a link
     * that had nothing to retry: T4 armed the schedule on the failure, the
     * schedule is live and expiring, and T7's `clean_leave == 0` is the only
     * thing standing between that schedule and a socket. A node that did not arm
     * it at all would pass the line above for the wrong reason. */
    arms = tf_count(a.out, "link_retry: peer=" NAME_B);
    TF_CHECK_MSG(arms == 1u,
                 "irc.a armed the retry ladder %llu times for a link that had "
                 "cleanly departed, expected the single arm T4 makes when the "
                 "socket closed: %s",
                 (unsigned long long)arms, a.out);
    TF_CHECK_MSG(strstr(a.out, "link_retry_exhausted: peer=" NAME_B) == NULL,
                 "irc.a spent a whole retry budget on a peer that said it was "
                 "leaving, which is the cost clean_leave exists to avoid: %s",
                 a.out);

    TF_CHECK_MSG(nf_stop(&a) == 0, "node " NAME_A " did not exit cleanly");
    TF_CHECK_MSG(nf_stop(&d) == 0, "node " NAME_D " did not exit cleanly");
    nf_free(&a);
    nf_free(&d);
}

int main(void)
{
    case_a_hint_is_recorded_and_never_dialled();
    case_clean_leave_is_not_a_failure();
    tf_done("peer_discovery");
    return 0;
}
