#!/usr/bin/env python3
"""check-docs-truth.py -- the NUMERIC claims in the docs, checked against the tree.

WHY THIS EXISTS
---------------
This project's rule is that a stale claim is worse than an absent one, and four
independent audits have found stale claims that nobody could see because nothing in the
build or the suite looked at the documents. The specific ones this script exists for:

  * `docs/SPEC_TRACKING.md` claimed **"39 tests: 31 passed, 8 skipped, 0 failed"**
    twice -- once in a table titled "How this was verified" and once inside a section
    titled "Test suite as it actually stands". The actual suite was 95 tests and 0
    skips. A heading that says "as it actually stands" is the last place a reader
    should find a number nobody re-checked.
  * `README.md` claimed the tree's newest tag was `v0.7.0-messaging`. It was
    `safety-net`, and before that `backup-before-claude-rewrite-3` -- neither of which
    is a phase tag, which is exactly why "the newest one" was wrong in a way nobody
    noticed.
  * `README.md` said "a green suite means the whole implemented surface is covered".
    14 of the registered tests are unit-style, a green run BOUNDS behaviour and does
    not bound coverage, and that inference is wrong. It is reworded in the same commit;
    this script cannot check it, and its own header says so rather than pretending the
    file covers prose.
  * `docs/DEVELOPMENT.md`'s FIRST verification command printed the wrong SHAs against
    its own correct table, because `%(objectname:short)` on an ANNOTATED tag yields
    the TAG OBJECT rather than the commit. That is now the generated table's problem
    and this script's to verify.

WHAT IS CHECKED
---------------
  1. EVERY test-count claim in `README.md` and `docs/SPEC_TRACKING.md` against
     `ctest -N`. The claims are FOUND by pattern, not by line number, so inserting a
     paragraph does not silently exempt one.
  2. Every "N skipped" claim against `tests/known_skips.txt` -- the permitted set --
     and, when a ctest log is supplied, against the log's own skip block.
  3. `README.md`'s "~N lines of C" against `wc -l` over `src/**.[ch]`. A CLAIMED
     approximation is checked as a band, not as an equality, because the claim is
     written as `~`; the band is stated below.
  4. `README.md`'s "the tree's newest tag is X" against
     `git for-each-ref --sort=-creatordate`, taking the FIRST ref. This is the check
     that catches a new tag appearing under a stale sentence.
  5. `docs/DEVELOPMENT.md`'s rollback table against
     `scripts/gen-rollback-table.py`. The table is generated by that script and
     committed, so "the table matches the repository" is a string equality against a
     regeneration -- which is the whole of the `make docs` invariant, made
     enforceable.

WHICH REPOSITORY, AND WHY IT IS NOT THIS CLONE
----------------------------------------------
Checks 4 and 5 used to read `refs/tags`, and that is the wrong repository. This
project carries tags that exist only on one developer's machine, so a clone with them
answers differently from a fresh one -- and the answer is then true of nobody. It was
not hypothetical: the machine this was fixed on held 11 tags and `origin` held 9, and
the two the clone had extra were enough to make README's "the tree's newest tag is
`safety-net`" sentence true locally and false everywhere else.

So both now ask the REMOTE, through `scripts/gen-rollback-table.py`:
`git ls-remote --tags origin` for the list, and a fetch into a private namespace
(`refs/ircserve-docstruth/tags`) for the dates and subjects that `ls-remote` does not
carry. A local tag cannot appear in that list, so it cannot change a verdict.

THE ADJACENT HAZARD, and it is the reason this is not done by ignoring tags. The
rollback table's SHAs and subjects are a documented claim about the repository too, and
a table that disagrees with `origin` is exactly what `make docs` and this check exist
to catch. So the generator was changed rather than bypassed: it still compares the
committed table byte for byte against a fresh regeneration, it now just regenerates
from the remote. Nothing was weakened, and the check is strictly more of an answer than
it was -- before, "the table agrees with the repository" meant "with the clone", which
was a statement about one machine wearing the words of a statement about all of them.

WHAT IS NOT CHECKED, AND IT IS WORTH BEING SPECIFIC
---------------------------------------------------
  * PROSE IN A SHIPPED SCRIPT, other than a test count. `scripts/` IS read now, and the
    extension is deliberately narrow: only the test count, which is the one number this
    script can compute. A general "N cells / N sites / N binaries" pattern was written
    and measured, and it matched 34 lines of which most were correct by definition --
    `gate.sh`'s matrix IS twelve cells, and the checkers' own docstrings quote stale
    numbers on purpose in order to say "this was wrong". A check red on correct lines
    gets deleted, and a deleted check catches nothing.
  * PROSE. "There is no v0.8.0 because nothing after Phase 5 was tagged" is a claim
    about what the table MEANS; a script that verified it would have to have an
    opinion about what a reader would conclude, and a check that encodes an opinion is
    a check that encodes a mistake. `src/tls_openssl.c`'s header claim about revocation
    is the same shape and lives in a C file, so no script in this tree can reach it;
    it is fixed by hand in the same commit and the manual is left as the mechanism.
  * PERCENTAGES AND APPROXIMATIONS other than the line count. "~43,800" is checked as
    a band because that is the claim's own hedge; a claim written as "~43,800" and a
    tree at 45,415 lines is TRUE, and a check demanding equality would have forced a
    lie in one direction or the other.
  * THE TEST COUNT AS A CONSTANT. The gate deliberately does not pin it -- tests get
    added, and a hardcoded number turns every addition into a gate failure while
    catching nothing. So this script checks the DOC against the tree, and never the
    tree against a number in this file. That asymmetry is the design.

HOW IT FINDS A BUILD TREE
------------------------
`ctest -N` needs one, and this script must not report clean when it cannot ask the
question. Order: `--build DIR`, then `$BUILD_DIR`, then `./build`, then the newest
`./build-gate/*`. None of them present is a FAILURE with a message saying which, not a
skip and not a pass -- a doc check that quietly checks nothing is the exact
decorative-assertion failure this file exists to end.

EXIT STATUS
-----------
0 when every claim found agrees. 1 with one line per disagreement, naming the file, the
claim as written, and the truth.
"""

import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

findings = []
checked = []


def read(rel):
    with open(os.path.join(ROOT, rel), "r", encoding="utf-8") as fh:
        return fh.read()


def finding(rel, claim, truth, why):
    findings.append((rel, claim, truth, why))


def note(rel, claim, why):
    checked.append((rel, claim, why))


# ---------------------------------------------------------------------------
# The tree's facts
# ---------------------------------------------------------------------------
def registered_tests(build):
    """`ctest -N`'s total, which is a fact about CONFIGURED tests."""
    out = subprocess.run(["ctest", "--test-dir", build, "-N"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        return None
    m = re.search(r"Total Tests:\s*(\d+)", out.stdout)
    return int(m.group(1)) if m else None


def permitted_skips():
    path = os.path.join(ROOT, "tests", "known_skips.txt")
    if not os.path.isfile(path):
        return None
    n = 0
    for line in open(path, "r", encoding="utf-8"):
        s = line.strip()
        if s and not s.startswith("#"):
            n += 1
    return n


def docs_remote():
    """Which remote the repository-state claims are read from.

    Overridable, because the fault that proves this file reads the right repository is
    "point it at the local clone" -- and a check that can only be proved by editing its
    own source has no proof. DOCS_TRUTH_REMOTE is a NAMED input to the check rather
    than a fault hook: `DOCS_TRUTH_REMOTE=. make docs-check` is a thing a person can
    legitimately want to run, and it asks the identical question of a different
    repository.
    """
    return os.environ.get("DOCS_TRUTH_REMOTE") or DEFAULT_DOCS_REMOTE


def src_lines():
    out = subprocess.run(
        ["bash", "-c",
         "find src -name '*.c' -o -name '*.h' | LC_ALL=C sort | xargs cat | wc -l"],
        cwd=ROOT, capture_output=True, text=True)
    try:
        return int(out.stdout.strip())
    except ValueError:
        return None


DEFAULT_DOCS_REMOTE = "origin"


def newest_tag():
    """The newest tag ON THE REMOTE, with the provenance that produced it.

    It used to be `git for-each-ref --sort=-creatordate --count=1 refs/tags`, which
    answers a question about THIS CLONE. A clone with a local-only tag answers that
    differently from a fresh one, so the verdict was a function of the machine rather
    than of the repository -- which is the whole of what changed here.

    It delegates rather than reimplementing, so there is exactly ONE place in the tree
    that knows how to read a remote's tags and exactly one answer. `ls-remote` alone
    cannot do this: it carries names and object SHAs and no dates, so the ordering the
    claim is about is not in its output.

    Returns (name, provenance) or (None, reason-on-stderr). None is NOT a skip: the
    caller turns it into a finding, because a doc check that cannot ask the question
    and reports clean is the decorative-assertion failure this file exists to end.
    """
    script = os.path.join(ROOT, "scripts", "gen-rollback-table.py")
    out = subprocess.run([sys.executable, script, "--newest-tag",
                          "--remote", docs_remote()],
                         capture_output=True, text=True)
    if out.returncode != 0:
        return None, (out.stdout + out.stderr).strip()
    name = out.stdout.strip().splitlines()[0] if out.stdout.strip() else None
    return name, out.stderr.strip()


def header_version():
    m = re.search(r'#\s*define\s+IRC_SERVE_VERSION\s+"([^"]+)"',
                  read("src/core/server.h"))
    return m.group(1) if m else None


# ---------------------------------------------------------------------------
# The claims
# ---------------------------------------------------------------------------
# `README.md`'s "92 tests, 0 skipped" and "| Tests | **92 passing, 0 skipped**".
RE_TEST_COUNT = re.compile(r'(\d+)\s+tests?,\s+0 skipped')
RE_TABLE_COUNT = re.compile(r'\|\s*Tests\s*\|\s*\*\*(\d+) passing,\s*(\d+) skipped\*\*')
# `SPEC_TRACKING.md`'s "39 tests: 31 passed, 8 skipped, 0 failed", twice.
RE_CENSUS = re.compile(r'(\d+) tests:\s*(\d+) passed,\s*(\d+) skipped,\s*(\d+) failed')
RE_LINES = re.compile(r'~([\d,]+)\s+lines of C')
RE_NEWEST = re.compile(r"newest tag is `([^`]+)`")

DOCS = ("README.md", "docs/SPEC_TRACKING.md", "docs/DEVELOPMENT.md")

# ---------------------------------------------------------------------------
# SHIPPED SCRIPTS ARE DOCS, AND THE ARGUMENT FOR ADDING THEM
# ---------------------------------------------------------------------------
# The third item this pass was asked to settle was whether to extend this check to
# `scripts/`, and the argument for it is not "a numeric claim in a shell script is
# prose too" -- it is that these scripts are SHIPPED. `scripts/gate.sh`,
# `scripts/build-debian-package.sh` and `scripts/gate-linux-cell.sh` are how the next
# person reproduces this project's green, and a comment in them is the only
# documentation that travels with the command. A stale count in one is not a typo in a
# private scratch file; it is the project's own definition of its gate, written down
# somewhere nobody diffs.
#
# WHAT IT COST TO FIND OUT, which is the evidence rather than the argument: this pass
# added `scripts/gate-linux-cell.sh`, and while reading the existing scripts for style
# it found `scripts/audit-teardown.py` asserting "macOS `leaks(1)` over all 98 binaries
# confirms it" -- TWICE, once in a comment and once in the printed output, with 100
# tests registered and 100 test binaries built. The number had been wrong since tests
# were added, in the one file whose entire job is to report what it did. Nothing checked
# it, because nothing read `scripts/`.
#
# The fix in that file was to delete the number rather than update it, and that is the
# right shape for the ones this check cannot compute: a count of "the test binaries" is
# true at every test count, and a check that demands it equal a number has to be
# re-derived every time a test is added. So the checks below are of two kinds:
#   * COMPUTABLE claims, which are compared against the tree, and
#   * FORBIDDEN hardcoded counts in shipped scripts, which are a FAILURE because the
#     only correct value of "N test binaries" is the one nobody has to write down.
#
# THE LIMIT, and it is a real one: this reads COMMENTS AND STRING LITERALS in shell and
# Python. It cannot tell a number in a comment from a number in a command, and it does
# not try -- the patterns below are anchored on prose ("all N binaries", "N cells",
# "N sites") rather than on any digit, so a `--timeout 300` is not a claim and is not
# flagged. A prose pattern that misses a phrasing nobody has hit is a check with a hole,
# and saying so is better than implying coverage.
SHIPPED_SCRIPTS = sorted(
    glob.glob(os.path.join(ROOT, "scripts", "*.sh"))
    + glob.glob(os.path.join(ROOT, "scripts", "*.py")))

# Prose claims about the TEST COUNT in a shipped script, and ONLY that count. This is
# the one number this script can compute (registered_tests() above), which is the whole
# reason it is the one being checked.
#
# A GENERAL "N builds / N cells / N sites" pattern was written and MEASURED, and it is
# not here: it matched 34 sites across scripts/, of which the overwhelming majority are
# legitimately-fixed numbers or a checker's own history. `gate.sh` says "12 cells"
# because the matrix IS twelve cells by definition; it says "16 cells" while explaining
# that discovery would give sixteen and that this is why the count is fixed; it says
# "13 cells" inside a comment about a hypothetical bad summary; `audit-teardown.py`'s
# docstring quotes "39 tests" and "95 tests" as the STALE CLAIMS it exists to catch. A
# check that is red on 30 correct lines is deleted inside one pass, and a deleted check
# catches nothing -- which is the same argument this file's own header makes about
# prose and about over-pinning. So the extension is the computable claim and nothing
# else.
#
# `\d+` in a comment is not matched here either: the CHECKERS' OWN files are excluded,
# because a checker quoting the wrong number in order to say "this was wrong" is doing
# its job, and a rule that flagged it would flag the very sentences that document it.
RE_SCRIPT_TESTCOUNT = re.compile(
    r"\b(\d+)\s+(?:tests?|test binaries)\b")

# A QUOTED MEASUREMENT IS NOT A CLAIM ABOUT NOW. `scripts/leaksweep.sh` records what a
# named CI run on a named date reported -- `100% tests passed, 0 tests failed out of
# 100` -- inside backticks. That is a quotation of a tool's output on a day, and it is
# exactly what should be in a comment: it is falsifiable against that run and it stops
# being a claim the moment the tree's test count moves. Matching it would mean the only
# way to keep this check green is to delete the project's record of what the oracle said,
# which is the opposite of what a documentation check is for.
#
# So a match inside a backtick span is skipped, and a match outside one is a CLAIM and is
# compared against the tree. The two are different kinds of sentence and a reader can
# tell them apart at a glance; a checker that could not would be a checker that had to
# guess, and this one does not.
# ACROSS LINES, which the first version of this did not do and the effect of which was
# that a quotation wrapped over two lines stopped being a quotation: the span is blanked
# over the whole text rather than per line, because a backtick pair in a wrapped
# comment is on two different lines.
#
# DOTALL, so a backtick span may contain newlines. Paired backticks, so an ODD number of
# them -- an unpaired backtick in prose -- leaves the rest of the file unquoted rather
# than blanking it to the end.
RE_BACKTICK_SPAN = re.compile(r"`[^`]*`", re.S)


def script_count_claims(text):
    """[(count, line_number, line)] for each test-count claim NOT inside backticks.

    Line numbers are recovered from the blanked text rather than from the original, which
    is why the blanking preserves every byte INCLUDING newlines: `re.sub` with a function
    returning spaces of the same length leaves the line structure byte-identical, so a
    match found in the blanked text sits at the same line in the original.
    """
    blanked = RE_BACKTICK_SPAN.sub(lambda mm: re.sub(r"[^\n]", " ", mm.group(0)), text)
    out = []
    for n, line in enumerate(blanked.split("\n"), 1):
        for m in RE_SCRIPT_TESTCOUNT.finditer(line):
            out.append((int(m.group(1)), n, text.split("\n")[n - 1].strip()))
    return out


def check_docs(build, log):
    ntests = registered_tests(build)
    nskips_permitted = permitted_skips()
    nlines = src_lines()
    tag, tag_where = newest_tag()

    if ntests is None:
        finding("README.md", "every test-count claim",
                "(unknown)",
                "ctest -N would not run in %s, so no test-count claim in any document "
                "could be checked. A doc check that cannot ask the question must fail "
                "rather than report clean -- point it at a configured build tree with "
                "--build DIR." % build)
        return

    for rel in DOCS:
        try:
            text = read(rel)
        except OSError:
            continue

        # 1. "<N> tests, 0 skipped"
        for m in RE_TEST_COUNT.finditer(text):
            got = int(m.group(1))
            note(rel, m.group(0), "test count vs ctest -N")
            if got != ntests:
                finding(rel, m.group(0), "%d tests" % ntests,
                        "the suite has %d registered tests and the document says %d. "
                        "This is the claim docs/SPEC_TRACKING.md made twice under the "
                        "heading 'as it actually stands', where a stale number is the "
                        "last place a reader will look for a current one."
                        % (ntests, got))

        # 2. "| Tests | **N passing, M skipped** |"
        for m in RE_TABLE_COUNT.finditer(text):
            got_p, got_s = int(m.group(1)), int(m.group(2))
            note(rel, m.group(0), "test count vs ctest -N")
            if got_p != ntests:
                finding(rel, m.group(0), "%d passing" % ntests,
                        "the suite has %d registered tests and the document says %d "
                        "passing." % (ntests, got_p))
            if got_s != nskips_permitted:
                finding(rel, m.group(0), "%d skipped" % nskips_permitted,
                        "tests/known_skips.txt permits %d skip(s) and the document "
                        "says %d. known_skips.txt is the SINGLE AUTHORITATIVE list "
                        "and this is the only machine-readable version of it."
                        % (nskips_permitted, got_s))

        # 3. the census form "<N> tests: <P> passed, <S> skipped, <F> failed"
        for m in RE_CENSUS.finditer(text):
            got = int(m.group(1))
            note(rel, m.group(0), "test census vs ctest -N")
            if got != ntests:
                finding(rel, m.group(0), "%d tests" % ntests,
                        "the suite has %d registered tests. The census form also "
                        "carries a skip count, and %s permits %d -- so the two halves "
                        "of this one line were both wrong and only the total was "
                        "checkable."
                        % (ntests, "tests/known_skips.txt", nskips_permitted or 0))

        # 4. "~N lines of C"
        for m in RE_LINES.finditer(text):
            claimed = int(m.group(1).replace(",", ""))
            note(rel, m.group(0), "line count vs wc -l over src/")
            if nlines is None:
                continue
            # THE BAND, and why: the claim is written as `~`, so equality would be
            # testing a different claim than the one made. 5% is narrow enough to
            # catch "this file was not updated for two phases of work" and wide enough
            # that an ordinary week of commits does not fail a document.
            if abs(nlines - claimed) > claimed * 0.05:
                finding(rel, m.group(0), "src/ is %d lines" % nlines,
                        "the claim is within 5%% of the tree and is not: %d against "
                        "%d. The band is 5%% because the claim is written as `~`; "
                        "equality would be testing a different claim than the one "
                        "made." % (claimed, nlines))

        # 5. "newest tag is `X`"
        for m in RE_NEWEST.finditer(text):
            # The `why` column names WHERE the answer came from. It is in the output
            # rather than only in a comment because the whole failure this check had
            # was invisible: a developer whose clone carried two extra tags saw a
            # green run of a check that was reading the wrong repository. A check that
            # prints which repository it consulted cannot be misread that way again,
            # and the next person to find this has the line to look at.
            where = tag_where or "an UNREADABLE source"
            note(rel, m.group(0), "newest tag vs %s" % where)
            if tag is None:
                finding(rel, m.group(0), "(unknown)",
                        "the repository's tags could not be read, so this claim is "
                        "UNCHECKED rather than confirmed: %s. Not skipping it: a doc "
                        "check that cannot ask the question must fail rather than "
                        "report clean." % where)
                continue
            if m.group(1) != tag:
                finding(rel, m.group(0), "the newest tag is `%s`" % tag,
                        "by creatordate, read from %s. A phase tag is a poor answer "
                        "here precisely because phase tags stopped being created "
                        "while other tags did not -- which is what made the sentence "
                        "wrong without anything looking wrong. NOTE THAT THIS IS THE "
                        "REPOSITORY AND NOT YOUR CLONE: a tag that exists only in a "
                        "local checkout cannot and does not change this answer."
                        % where)

    # 6. the generated rollback table
    check_rollback_table()


BEGIN = "<!-- BEGIN GENERATED: rollback-table (scripts/gen-rollback-table.py; `make docs`) -->"
END = "<!-- END GENERATED: rollback-table -->"


def check_scripts(build):
    """Test-count claims in SHIPPED scripts, against the registered test count.

    WHY THIS EXISTS IS IN THE HEADER, and the short version is that a stale count in a
    shipped script is a stale count in the project's own definition of its gate. It was
    not hypothetical: `scripts/audit-teardown.py` said "all 98 binaries" twice, with
    100 registered.

    WHAT IT DOES NOT CHECK, and the limits are stated because the extension is narrow on
    purpose:

      * ONLY THE TEST COUNT. A general "N cells / N sites" pattern was written and
        measured, and it matched 34 lines of which most were correct by definition --
        `gate.sh`'s matrix IS twelve cells, and the checkers' docstrings quote stale
        numbers on purpose. A check red on correct lines gets deleted, and a deleted
        check catches nothing.
      * IT DOES NOT PARSE SHELL. It reads text and looks for prose shapes. It cannot
        tell a number in a comment from a number in a command; the patterns are anchored
        on words so that `--timeout 300` is not a claim and is not flagged.
      * A CLAIM IN BACKTICKS IS A QUOTATION and is skipped, because recording what a
        named CI run reported on a named date is what a comment is for.
      * THE CHECKERS' OWN FILES ARE EXCLUDED, because a checker quoting the wrong number
        in order to say "this was wrong" is doing its job.
    """
    ntests = registered_tests(build)
    if ntests is None:
        sys.stderr.write(
            "check-docs-truth: FAIL: cannot ask `ctest -N` how many tests there are, so "
            "the shipped scripts' test-count claims would go UNCHECKED. Not skipping "
            "them: a check that quietly checks nothing is the failure this script "
            "exists to end.\n")
        findings.append(("scripts/*.sh", "every test-count claim in a shipped script",
                         "cannot be computed", "ctest -N could not be run"))
        return
    scripts = [p for p in SHIPPED_SCRIPTS
               if not os.path.basename(p).startswith("check-")]
    if not scripts:
        sys.stderr.write(
            "check-docs-truth: FAIL: no shipped scripts found under scripts/, so this "
            "check would pass vacuously on the thing it exists to cover.\n")
        return
    for path in scripts:
        rel = os.path.relpath(path, ROOT)
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        for count, lineno, line in script_count_claims(text):
            if count == ntests:
                note(rel, line[:52],
                     "%s: a test count that agrees with ctest -N's %d" % (rel, ntests))
                continue
            finding(rel,
                    "%s:%d: %s" % (rel, lineno, line),
                    "%d registered test(s)" % ntests,
                    "a shipped script's prose says %d tests. Scripts/ is read by this "
                    "check because a shipped script is documentation the next person "
                    "reproduces the gate from, and a stale count there rots unnoticed. "
                    "Either correct the number or delete it: \"the test binaries\" is "
                    "true at every test count and needs no maintenance." % count)


def check_rollback_table():
    """The table equals a fresh regeneration, byte for byte.

    This is the `make docs` invariant made enforceable, and it is the check that
    replaces a manual "AND IF YOU ADD A TAG, ADD IT HERE".

    THE ADJACENT HAZARD IS NOT AVOIDED BY BEING CAREFUL HERE. The table's SHAs and
    subjects are a claim about the repository as much as the tag list is, so a table
    that disagrees with `origin` has to be caught, and it is: the generator now
    regenerates FROM origin, and the comparison below is still a byte-for-byte
    equality. The change made the question better-posed; it did not make it
    easier to pass.
    """
    out = subprocess.run([sys.executable,
                          os.path.join(ROOT, "scripts", "gen-rollback-table.py"),
                          "--remote", docs_remote()],
                         capture_output=True, text=True)
    if out.returncode != 0:
        finding("docs/DEVELOPMENT.md", "the generated rollback table",
                "(regeneration failed)",
                "scripts/gen-rollback-table.py exited %d: %s"
                % (out.returncode, (out.stdout + out.stderr).strip()[:300]))
        return
    want = out.stdout.strip()
    doc = read("docs/DEVELOPMENT.md")
    if BEGIN not in doc or END not in doc:
        finding("docs/DEVELOPMENT.md", "the generated rollback table",
                "(no markers)",
                "the generated-table markers are absent, so there is nothing to "
                "compare. A rollback table with no check on it is the state this "
                "check exists to end.")
        return
    m = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), doc, re.S)
    got = m.group(1).strip()
    note("docs/DEVELOPMENT.md", "the generated rollback table",
         "regenerated from remote '%s'" % docs_remote())
    if got != want:
        want_tags = re.findall(r"^\| `([^`]+)`", want, re.M)
        got_tags = re.findall(r"^\| `([^`]+)`", got, re.M)
        only_want = [t for t in want_tags if t not in got_tags]
        only_got = [t for t in got_tags if t not in want_tags]
        if only_want or only_got:
            finding("docs/DEVELOPMENT.md", "the rollback table's tag list",
                    "%d tags in remote '%s'" % (len(want_tags), docs_remote()),
                    "in the remote but not in the table: %s; in the table but not "
                    "in the remote: %s. Run `make docs`. A tag that exists only in "
                    "a local checkout is not a rollback point for anyone reading the "
                    "document, so it does not belong in it."
                    % (", ".join(only_want) or "(none)",
                       ", ".join(only_got) or "(none)"))
        else:
            finding("docs/DEVELOPMENT.md", "the rollback table's contents",
                    "a fresh regeneration",
                    "the same tags with different SHAs or subjects, so the table is "
                    "stale in content. Run `make docs`. This is the second reason the "
                    "old table was wrong: the tags were right and the objects were "
                    "not, which is invisible to a check that only counts tags.")


def main():
    build = None
    explicit = False
    log = None
    args = sys.argv[1:]
    for i, a in enumerate(args):
        if a == "--build" and i + 1 < len(args):
            build = args[i + 1]
            explicit = True
        elif a == "--ctest-log" and i + 1 < len(args):
            log = args[i + 1]

    def configured(d):
        return bool(d) and os.path.isdir(d) and \
            os.path.isfile(os.path.join(d, "CTestTestfile.cmake"))

    # AN EXPLICIT --build IS NEVER SILENTLY SUBSTITUTED. The first version of this
    # fell through to the discovery chain when the directory it was GIVEN was not a
    # build tree, so `--build /tmp/nonsense` answered from a stale `./build-gate/*`
    # left over from an earlier matrix and reported four "stale claims" that were
    # simply this tree's count. A wrong answer dressed as a check is worse than a
    # refusal, and the refusal is one line.
    if explicit and not configured(build):
        sys.stderr.write(
            "check-docs-truth: FAIL: --build %s is not a configured build tree (no "
            "CTestTestfile.cmake), so `ctest -N` cannot be asked how many tests there "
            "are. Not falling back to another tree: substituting one silently "
            "answers the question from somewhere the caller did not name.\n"
            % build)
        return 1

    if not configured(build):
        build = os.environ.get("BUILD_DIR")
    if not configured(build):
        for cand in ([os.path.join(ROOT, "build")] +
                     sorted(glob.glob(os.path.join(ROOT, "build-gate", "*")),
                            key=os.path.getmtime, reverse=True)):
            if configured(cand):
                build = cand
                break
    if not configured(build):
        sys.stderr.write(
            "check-docs-truth: FAIL: no configured build tree, so `ctest -N` cannot be "
            "asked how many tests there are and EVERY test-count claim in the "
            "documents would go unchecked. Pass --build DIR or set BUILD_DIR.\n"
            "    Tried: $BUILD_DIR, ./build, ./build-gate/*\n")
        return 1

    check_docs(build, log)
    check_scripts(build)

    print("check-docs-truth: %d numeric claim(s) in README.md, "
          "docs/SPEC_TRACKING.md, docs/DEVELOPMENT.md and %d shipped script(s) "
          "checked against %s."
          % (len(checked), len(SHIPPED_SCRIPTS), os.path.relpath(build, ROOT)))
    print("check-docs-truth: repository-state claims (tags, rollback table) were read "
          "from remote '%s', NOT from this clone's refs/tags -- a tag that exists only "
          "in a local checkout cannot change a verdict here."
          % docs_remote())
    for rel, claim, why in checked:
        print("    %-22s %-52s  %s" % (rel, claim[:52], why))
    if findings:
        sys.stderr.write("check-docs-truth: FAIL: %d stale claim(s):\n" % len(findings))
        for rel, claim, truth, why in findings:
            sys.stderr.write("    %s\n" % rel)
            sys.stderr.write("      claim: %s\n" % claim)
            sys.stderr.write("      truth: %s\n" % truth)
            sys.stderr.write("      %s\n" % why)
        return 1
    print("    NOT CHECKED HERE, and said so rather than implied: PROSE. The claim "
          "that\n    nothing after Phase 5 was tagged is a claim about what the table "
          "MEANS,\n    and a script with an opinion about that is a script with an "
          "opinion in it.\n    `src/tls_openssl.c`'s revocation claim lives in a C "
          "file and is fixed by hand.")
    return 0


if __name__ == "__main__":
    sys.exit(main())