#!/usr/bin/env python3
"""check-docs-truth.py -- the NUMERIC claims in the docs, checked against the tree.

WHY THIS EXISTS
---------------
This project's rule is that a stale claim is worse than an absent one, and four
independent audits have found stale claims that nobody could see because nothing in the
build or the suite looked at the documents. The specific ones this script exists for:

  * `docs/SPEC_TRACKING.md` claimed **"39 tests: 31 passed, 8 skipped, 0 failed"**
    twice -- once in a table titled "How this was verified" and once inside a section
    titled "Test suite as it actually stands". The actual suite was 95 tests and 0
    skips. A heading that says "as it actually stands" is the last place a reader
    should find a number nobody re-checked.
  * `README.md` claimed the tree's newest tag was `v0.7.0-messaging`. It was
    `safety-net`, and before that `backup-before-claude-rewrite-3` -- neither of which
    is a phase tag, which is exactly why "the newest one" was wrong in a way nobody
    noticed.
  * `README.md` said "a green suite means the whole implemented surface is covered".
    14 of the registered tests are unit-style, a green run BOUNDS behaviour and does
    not bound coverage, and that inference is wrong. It is reworded in the same commit;
    this script cannot check it, and its own header says so rather than pretending the
    file covers prose.
  * `docs/DEVELOPMENT.md`'s FIRST verification command printed the wrong SHAs against
    its own correct table, because `%(objectname:short)` on an ANNOTATED tag yields
    the TAG OBJECT rather than the commit. That is now the generated table's problem
    and this script's to verify.

WHAT IS CHECKED
---------------
  1. EVERY test-count claim in `README.md` and `docs/SPEC_TRACKING.md` against
     `ctest -N`. The claims are FOUND by pattern, not by line number, so inserting a
     paragraph does not silently exempt one.
  2. Every "N skipped" claim against `tests/known_skips.txt` -- the permitted set --
     and, when a ctest log is supplied, against the log's own skip block.
  3. `README.md`'s "~N lines of C" against `wc -l` over `src/**.[ch]`. A CLAIMED
     approximation is checked as a band, not as an equality, because the claim is
     written as `~`; the band is stated below.
  4. `README.md`'s "the tree's newest tag is X" against
     `git for-each-ref --sort=-creatordate`, taking the FIRST ref. This is the check
     that catches a new tag appearing under a stale sentence.
  5. `docs/DEVELOPMENT.md`'s rollback table against
     `scripts/gen-rollback-table.py`. The table is generated by that script and
     committed, so "the table matches the repository" is a string equality against a
     regeneration -- which is the whole of the `make docs` invariant, made
     enforceable.

WHAT IS NOT CHECKED, AND IT IS WORTH BEING SPECIFIC
---------------------------------------------------
  * PROSE. "There is no v0.8.0 because nothing after Phase 5 was tagged" is a claim
    about what the table MEANS; a script that verified it would have to have an
    opinion about what a reader would conclude, and a check that encodes an opinion is
    a check that encodes a mistake. `src/tls_openssl.c`'s header claim about revocation
    is the same shape and lives in a C file, so no script in this tree can reach it;
    it is fixed by hand in the same commit and the manual is left as the mechanism.
  * PERCENTAGES AND APPROXIMATIONS other than the line count. "~43,800" is checked as
    a band because that is the claim's own hedge; a claim written as "~43,800" and a
    tree at 45,415 lines is TRUE, and a check demanding equality would have forced a
    lie in one direction or the other.
  * THE TEST COUNT AS A CONSTANT. The gate deliberately does not pin it -- tests get
    added, and a hardcoded number turns every addition into a gate failure while
    catching nothing. So this script checks the DOC against the tree, and never the
    tree against a number in this file. That asymmetry is the design.

HOW IT FINDS A BUILD TREE
------------------------
`ctest -N` needs one, and this script must not report clean when it cannot ask the
question. Order: `--build DIR`, then `$BUILD_DIR`, then `./build`, then the newest
`./build-gate/*`. None of them present is a FAILURE with a message saying which, not a
skip and not a pass -- a doc check that quietly checks nothing is the exact
decorative-assertion failure this file exists to end.

EXIT STATUS
-----------
0 when every claim found agrees. 1 with one line per disagreement, naming the file, the
claim as written, and the truth.
"""

import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

findings = []
checked = []


def read(rel):
    with open(os.path.join(ROOT, rel), "r", encoding="utf-8") as fh:
        return fh.read()


def finding(rel, claim, truth, why):
    findings.append((rel, claim, truth, why))


def note(rel, claim, why):
    checked.append((rel, claim, why))


# ---------------------------------------------------------------------------
# The tree's facts
# ---------------------------------------------------------------------------
def registered_tests(build):
    """`ctest -N`'s total, which is a fact about CONFIGURED tests."""
    out = subprocess.run(["ctest", "--test-dir", build, "-N"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        return None
    m = re.search(r"Total Tests:\s*(\d+)", out.stdout)
    return int(m.group(1)) if m else None


def permitted_skips():
    path = os.path.join(ROOT, "tests", "known_skips.txt")
    if not os.path.isfile(path):
        return None
    n = 0
    for line in open(path, "r", encoding="utf-8"):
        s = line.strip()
        if s and not s.startswith("#"):
            n += 1
    return n


def src_lines():
    out = subprocess.run(
        ["bash", "-c",
         "find src -name '*.c' -o -name '*.h' | LC_ALL=C sort | xargs cat | wc -l"],
        cwd=ROOT, capture_output=True, text=True)
    try:
        return int(out.stdout.strip())
    except ValueError:
        return None


def newest_tag():
    out = subprocess.run(
        ["git", "-C", ROOT, "for-each-ref", "--sort=-creatordate",
         "--count=1", "--format=%(refname:short)", "refs/tags"],
        capture_output=True, text=True)
    t = out.stdout.strip().splitlines()
    return t[0] if t else None


def header_version():
    m = re.search(r'#\s*define\s+IRC_SERVE_VERSION\s+"([^"]+)"',
                  read("src/core/server.h"))
    return m.group(1) if m else None


# ---------------------------------------------------------------------------
# The claims
# ---------------------------------------------------------------------------
# `README.md`'s "92 tests, 0 skipped" and "| Tests | **92 passing, 0 skipped**".
RE_TEST_COUNT = re.compile(r'(\d+)\s+tests?,\s+0 skipped')
RE_TABLE_COUNT = re.compile(r'\|\s*Tests\s*\|\s*\*\*(\d+) passing,\s*(\d+) skipped\*\*')
# `SPEC_TRACKING.md`'s "39 tests: 31 passed, 8 skipped, 0 failed", twice.
RE_CENSUS = re.compile(r'(\d+) tests:\s*(\d+) passed,\s*(\d+) skipped,\s*(\d+) failed')
RE_LINES = re.compile(r'~([\d,]+)\s+lines of C')
RE_NEWEST = re.compile(r"newest tag is `([^`]+)`")

DOCS = ("README.md", "docs/SPEC_TRACKING.md", "docs/DEVELOPMENT.md")


def check_docs(build, log):
    ntests = registered_tests(build)
    nskips_permitted = permitted_skips()
    nlines = src_lines()
    tag = newest_tag()

    if ntests is None:
        finding("README.md", "every test-count claim",
                "(unknown)",
                "ctest -N would not run in %s, so no test-count claim in any document "
                "could be checked. A doc check that cannot ask the question must fail "
                "rather than report clean -- point it at a configured build tree with "
                "--build DIR." % build)
        return

    for rel in DOCS:
        try:
            text = read(rel)
        except OSError:
            continue

        # 1. "<N> tests, 0 skipped"
        for m in RE_TEST_COUNT.finditer(text):
            got = int(m.group(1))
            note(rel, m.group(0), "test count vs ctest -N")
            if got != ntests:
                finding(rel, m.group(0), "%d tests" % ntests,
                        "the suite has %d registered tests and the document says %d. "
                        "This is the claim docs/SPEC_TRACKING.md made twice under the "
                        "heading 'as it actually stands', where a stale number is the "
                        "last place a reader will look for a current one."
                        % (ntests, got))

        # 2. "| Tests | **N passing, M skipped** |"
        for m in RE_TABLE_COUNT.finditer(text):
            got_p, got_s = int(m.group(1)), int(m.group(2))
            note(rel, m.group(0), "test count vs ctest -N")
            if got_p != ntests:
                finding(rel, m.group(0), "%d passing" % ntests,
                        "the suite has %d registered tests and the document says %d "
                        "passing." % (ntests, got_p))
            if got_s != nskips_permitted:
                finding(rel, m.group(0), "%d skipped" % nskips_permitted,
                        "tests/known_skips.txt permits %d skip(s) and the document "
                        "says %d. known_skips.txt is the SINGLE AUTHORITATIVE list "
                        "and this is the only machine-readable version of it."
                        % (nskips_permitted, got_s))

        # 3. the census form "<N> tests: <P> passed, <S> skipped, <F> failed"
        for m in RE_CENSUS.finditer(text):
            got = int(m.group(1))
            note(rel, m.group(0), "test census vs ctest -N")
            if got != ntests:
                finding(rel, m.group(0), "%d tests" % ntests,
                        "the suite has %d registered tests. The census form also "
                        "carries a skip count, and %s permits %d -- so the two halves "
                        "of this one line were both wrong and only the total was "
                        "checkable."
                        % (ntests, "tests/known_skips.txt", nskips_permitted or 0))

        # 4. "~N lines of C"
        for m in RE_LINES.finditer(text):
            claimed = int(m.group(1).replace(",", ""))
            note(rel, m.group(0), "line count vs wc -l over src/")
            if nlines is None:
                continue
            # THE BAND, and why: the claim is written as `~`, so equality would be
            # testing a different claim than the one made. 5% is narrow enough to
            # catch "this file was not updated for two phases of work" and wide enough
            # that an ordinary week of commits does not fail a document.
            if abs(nlines - claimed) > claimed * 0.05:
                finding(rel, m.group(0), "src/ is %d lines" % nlines,
                        "the claim is within 5%% of the tree and is not: %d against "
                        "%d. The band is 5%% because the claim is written as `~`; "
                        "equality would be testing a different claim than the one "
                        "made." % (claimed, nlines))

        # 5. "newest tag is `X`"
        for m in RE_NEWEST.finditer(text):
            note(rel, m.group(0), "newest tag vs git for-each-ref --sort=-creatordate")
            if tag is not None and m.group(1) != tag:
                finding(rel, m.group(0), "the newest tag is `%s`" % tag,
                        "by creatordate. A phase tag is a poor answer here precisely "
                        "because phase tags stopped being created while other tags "
                        "did not -- which is what made the sentence wrong without "
                        "anything looking wrong.")

    # 6. the generated rollback table
    check_rollback_table()


BEGIN = "<!-- BEGIN GENERATED: rollback-table (scripts/gen-rollback-table.py; `make docs`) -->"
END = "<!-- END GENERATED: rollback-table -->"


def check_rollback_table():
    """The table equals a fresh regeneration, byte for byte.

    This is the `make docs` invariant made enforceable, and it is the check that
    replaces a manual "AND IF YOU ADD A TAG, ADD IT HERE".
    """
    out = subprocess.run([sys.executable,
                          os.path.join(ROOT, "scripts", "gen-rollback-table.py")],
                         capture_output=True, text=True)
    if out.returncode != 0:
        finding("docs/DEVELOPMENT.md", "the generated rollback table",
                "(regeneration failed)",
                "scripts/gen-rollback-table.py exited %d: %s"
                % (out.returncode, (out.stdout + out.stderr).strip()[:300]))
        return
    want = out.stdout.strip()
    doc = read("docs/DEVELOPMENT.md")
    if BEGIN not in doc or END not in doc:
        finding("docs/DEVELOPMENT.md", "the generated rollback table",
                "(no markers)",
                "the generated-table markers are absent, so there is nothing to "
                "compare. A rollback table with no check on it is the state this "
                "check exists to end.")
        return
    m = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), doc, re.S)
    got = m.group(1).strip()
    note("docs/DEVELOPMENT.md", "the generated rollback table",
         "regenerated by scripts/gen-rollback-table.py")
    if got != want:
        want_tags = re.findall(r"^\| `([^`]+)`", want, re.M)
        got_tags = re.findall(r"^\| `([^`]+)`", got, re.M)
        only_want = [t for t in want_tags if t not in got_tags]
        only_got = [t for t in got_tags if t not in want_tags]
        if only_want or only_got:
            finding("docs/DEVELOPMENT.md", "the rollback table's tag list",
                    "%d tags in the repository" % len(want_tags),
                    "in the repository but not in the table: %s; in the table but not "
                    "in the repository: %s. Run `make docs`."
                    % (", ".join(only_want) or "(none)",
                       ", ".join(only_got) or "(none)"))
        else:
            finding("docs/DEVELOPMENT.md", "the rollback table's contents",
                    "a fresh regeneration",
                    "the same tags with different SHAs or subjects, so the table is "
                    "stale in content. Run `make docs`. This is the second reason the "
                    "old table was wrong: the tags were right and the objects were "
                    "not, which is invisible to a check that only counts tags.")


def main():
    build = None
    explicit = False
    log = None
    args = sys.argv[1:]
    for i, a in enumerate(args):
        if a == "--build" and i + 1 < len(args):
            build = args[i + 1]
            explicit = True
        elif a == "--ctest-log" and i + 1 < len(args):
            log = args[i + 1]

    def configured(d):
        return bool(d) and os.path.isdir(d) and \
            os.path.isfile(os.path.join(d, "CTestTestfile.cmake"))

    # AN EXPLICIT --build IS NEVER SILENTLY SUBSTITUTED. The first version of this
    # fell through to the discovery chain when the directory it was GIVEN was not a
    # build tree, so `--build /tmp/nonsense` answered from a stale `./build-gate/*`
    # left over from an earlier matrix and reported four "stale claims" that were
    # simply this tree's count. A wrong answer dressed as a check is worse than a
    # refusal, and the refusal is one line.
    if explicit and not configured(build):
        sys.stderr.write(
            "check-docs-truth: FAIL: --build %s is not a configured build tree (no "
            "CTestTestfile.cmake), so `ctest -N` cannot be asked how many tests there "
            "are. Not falling back to another tree: substituting one silently "
            "answers the question from somewhere the caller did not name.\n"
            % build)
        return 1

    if not configured(build):
        build = os.environ.get("BUILD_DIR")
    if not configured(build):
        for cand in ([os.path.join(ROOT, "build")] +
                     sorted(glob.glob(os.path.join(ROOT, "build-gate", "*")),
                            key=os.path.getmtime, reverse=True)):
            if configured(cand):
                build = cand
                break
    if not configured(build):
        sys.stderr.write(
            "check-docs-truth: FAIL: no configured build tree, so `ctest -N` cannot be "
            "asked how many tests there are and EVERY test-count claim in the "
            "documents would go unchecked. Pass --build DIR or set BUILD_DIR.\n"
            "    Tried: $BUILD_DIR, ./build, ./build-gate/*\n")
        return 1

    check_docs(build, log)

    print("check-docs-truth: %d numeric claim(s) in README.md, "
          "docs/SPEC_TRACKING.md and docs/DEVELOPMENT.md checked against %s."
          % (len(checked), os.path.relpath(build, ROOT)))
    for rel, claim, why in checked:
        print("    %-22s %-52s  %s" % (rel, claim[:52], why))
    if findings:
        sys.stderr.write("check-docs-truth: FAIL: %d stale claim(s):\n" % len(findings))
        for rel, claim, truth, why in findings:
            sys.stderr.write("    %s\n" % rel)
            sys.stderr.write("      claim: %s\n" % claim)
            sys.stderr.write("      truth: %s\n" % truth)
            sys.stderr.write("      %s\n" % why)
        return 1
    print("    NOT CHECKED HERE, and said so rather than implied: PROSE. The claim "
          "that\n    nothing after Phase 5 was tagged is a claim about what the table "
          "MEANS,\n    and a script with an opinion about that is a script with an "
          "opinion in it.\n    `src/tls_openssl.c`'s revocation claim lives in a C "
          "file and is fixed by hand.")
    return 0


if __name__ == "__main__":
    sys.exit(main())