#!/usr/bin/env python3
"""check-packaging.py -- every packaging claim verifiable WITHOUT a Debian.

WHY THIS EXISTS
---------------
Issue #48 is the oldest open issue in this project and the only one that needs an
environment this machine does not have: there is no `dpkg-buildpackage`, no `dh` and
no lintian here, and LeakSanitizer's absence on Darwin is the same shape of problem --
a check that can only run in one place, which therefore does not run at all on the
machine where the work happens.

The project's rule is that a stale claim is worse than an absent one, and the claim
this replaces is the worst kind: "packaging/debian/rules created (basic dh pattern)".
A file existing is not a verification. So this script verifies everything that CAN be
verified without Debian, permanently, and prints the residue -- the part that needs a
Debian -- as part of its own output rather than leaving it in an issue.

WHAT IS CHECKED, AND EACH ITEM IS A THING THAT COULD BE WRONG
-------------------------------------------------------------
  1. `packaging/debian/changelog` PARSES as a Debian changelog entry: source name,
     version, distribution, urgency, an RFC 2822 signature line, and a date whose
     WEEKDAY MATCHES ITS DAY OF MONTH. The last one is not pedantry -- a changelog
     date is generated by `dch`, and a hand-written one with the wrong weekday is
     accepted by every parser and rejected by `dpkg-source`'s strictness in some
     versions, so a typo here is invisible until a Debian machine sees it.
  2. THE CHANGELOG'S VERSION IS THE HEADER'S. `IRC_SERVE_VERSION` in
     `src/core/server.h` is this project's ONE version definition; the Arch PKGBUILD
     derives from it and the Debian changelog records it. `tests/integration/
     test_version_truth.c` already asserts both -- this is the same claim from the
     packaging side, kept here so that a failure names the packaging file rather than
     the test.
  3. `packaging/arch/PKGBUILD`'s `pkgver` DERIVATION RUNS AND PRODUCES THAT
     VERSION. Not "the file mentions the header": the `sed` is executed, because a
     BSD-vs-GNU regex difference produces an EMPTY match rather than an error, and
     `makepkg` turns an empty `pkgver` into a malformed package instead of a refusal.
  4. `packaging/debian/rules` IS VALID MAKE, and its `dh` overrides expand. Verified
     with `make -n` against a STUB `dh` on PATH, so the rules file's own syntax and
     its target names are exercised without debhelper installed. `override_` on a
     target debhelper does not have is silently ignored by `dh`, so "the override is
     spelled right" is a claim worth checking.
  5. THE BINARY'S INSTALL RULE EXISTS. `install(TARGETS irc-serve RUNTIME DESTINATION
     bin)` is the whole of "the package contains the executable"; without it a
     successful `dh_auto_install` produces a `.deb` with no program in it, and the
     only way to find that out is to open the `.deb`.
  6. THE CONTROL FILE'S REQUIRED FIELDS ARE PRESENT: `Source`, `Section`,
     `Maintainer`, `Build-Depends` naming `debhelper-compat`, and a `Package:` stanza
     with `Architecture` and `Depends`. Missing any of them is a `dpkg-buildpackage`
     error with a message that does not name the file.

WHAT IS NOT CHECKED, AND THIS SCRIPT PRINTS IT RATHER THAN LEAVING IT TO AN ISSUE
---------------------------------------------------------------------------------
This is the point of the script, so it is worth reading exactly:

  * `dpkg-source -b` / `dpkg-buildpackage`, i.e. whether a source or binary package
    can be produced AT ALL.
  * `dh_auto_configure`'s and `dh_auto_build`'s real invocations, i.e. whether cmake
    accepts the flags the rules file passes.
  * WHAT THE PRODUCED `.deb` CONTAINS -- the executable, its shared-library
    dependencies, and the `${shlibs:Depends}` substitution.
  * `${shlibs:Depends}` RESOLUTION, which needs `dpkg-shlibdeps` and therefore the
    built library or binary.
  * `lintian`, and therefore Debian POLICY compliance (the absence of
    `debian/copyright` and of `debian/source/format` is a policy finding that only
    lintian reports).
  * ANYTHING ABOUT `makepkg` on Arch, for the same reason in the other direction.

The script exits 0 on success and prints the residue, so "the check passed" and "the
packaging is verified" are not the same claim and cannot be mistaken for one another.

EXIT STATUS
-----------
0 when every check above passes. 1 with a per-check report otherwise. A missing
`packaging/` directory is a FAILURE and not a skip: a check that cannot find the thing
it checks is not a check that passed.
"""

import os
import re
import subprocess
import sys
import tempfile
from email.utils import parsedate_to_datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEB = os.path.join(ROOT, "packaging", "debian")
ARCH = os.path.join(ROOT, "packaging", "arch")
HEADER = os.path.join(ROOT, "src", "core", "server.h")

failures = []
notes = []


def fail(what, why):
    failures.append((what, why))


def header_version():
    """The one version definition, read out of the header the way CMake reads it."""
    src = open(HEADER, "r", encoding="utf-8", errors="replace").read()
    m = re.search(r'#\s*define\s+IRC_SERVE_VERSION\s+"irc-serve-([0-9]+\.[0-9]+\.[0-9]+)"', src)
    if m is None:
        fail("header version",
             "src/core/server.h does not define IRC_SERVE_VERSION in the shape "
             "`irc-serve-X.Y.Z`. Every other version claim depends on this one.")
        return None
    return m.group(1)


def check_changelog(version):
    path = os.path.join(DEB, "changelog")
    if not os.path.isfile(path):
        fail("debian/changelog", "%s does not exist." % path)
        return None
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    # The HEADER and the SIGNATURE are parsed separately rather than as one regex,
    # because the body between them is free-form and a single pattern over all three
    # is a pattern that fails on a bullet list for a reason that has nothing to do with
    # the header. The first version of this did exactly that and reported a grammar
    # failure against a changelog that is correct.
    m = re.match(r'^(?P<pkg>[a-z0-9][a-z0-9+.-]*)\s+\((?P<ver>[^)]+)\)\s+'
                 r'(?P<dist>[a-z0-9-]+);\s+urgency=(?P<urg>\w+)\n', text)
    # LEADING WHITESPACE BEFORE `--` IS ALLOWED and dpkg-source writes it, so the
    # pattern does not anchor the `--` to the start of a line. The first version did,
    # and reported a grammar failure against a changelog that is correct.
    sig = re.search(r'^[ \t]*--\s(?P<who>[^\n]*?)\s\s(?P<date>[^\n]+?)[ \t]*$',
                    text, re.M)
    if m is None or sig is None:
        fail("debian/changelog grammar",
             "the file does not parse as a Debian changelog entry. `dpkg-parsechangelog` "
             "is not available here, so the grammar was parsed by hand: a source name, "
             "`(version)`, a distribution, `urgency=`, an indented body, then a `-- "
             "signer  RFC2822 date` line. Whatever does not match is the thing to fix.")
        return None
    # And the body between them must be indented or blank, which is the one
    # structural rule the two half-parses do not cover.
    m = re.match(r'^(?P<pkg>[a-z0-9][a-z0-9+.-]*)\s+\((?P<ver>[^)]+)\)\s+'
                 r'(?P<dist>[a-z0-9-]+);\s+urgency=(?P<urg>\w+)\n', text)
    # And the body between them must be indented or blank, which is the one
    # structural rule the two half-parses do not cover.
    body = text[m.end():sig.start()]
    for line in body.split("\n"):
        if line and not line.startswith((" ", "\t")):
            fail("debian/changelog body",
                 "a body line is neither blank nor indented: %r. dpkg-source requires "
                 "every continuation line to start with whitespace." % line[:60])
            break

    ver = m.group("ver")
    if version is not None and ver.rsplit("-", 1)[0] != version:
        fail("debian/changelog version",
             "the changelog says %s and src/core/server.h says %s. The changelog is a "
             "RECORD and not a derivation -- it is what was uploaded -- so it is "
             "updated rather than computed, but a disagreement between the two is a "
             "package claiming a version its binary does not report." % (ver, version))

    try:
        when = parsedate_to_datetime(sig.group("date"))
    except Exception as exc:  # noqa: BLE001 - any parse failure is the finding
        fail("debian/changelog date",
             "the signature line's date does not parse as RFC 2822: %r (%s)."
             % (sig.group("date"), exc))
        return ver

    # THE WEEKDAY CHECK, which is the one no parser does for you.
    stated = when.strftime("%a")
    if not sig.group("date").startswith(stated + ","):
        fail("debian/changelog weekday",
             "the date `%s` says %s but that day of that month was a %s. Every parser "
             "accepts it; some dpkg-source versions do not."
             % (sig.group("date"), stated, when.strftime("%A")))

    # THE NATIVE/REVISION PAIRING, which item 4 below depends on.
    native = "-" not in ver
    fmt = os.path.join(DEB, "source", "format")
    if not os.path.isfile(fmt):
        notes.append(
            "debian/source/format is ABSENT, so dpkg-source assumes 1.0, which is a "
            "NATIVE format and requires a version with no Debian revision. The "
            "changelog version is %s (%s). That pairing is what makes `dpkg-source -b` "
            "and any default `dpkg-buildpackage` fail; `dpkg-buildpackage -b` skips "
            "the source package and may work. NOT CHECKED HERE -- there is no "
            "dpkg-source on this platform -- and NOT FIXED HERE, because choosing "
            "between a native `0.1.0` and a `3.0 (quilt)` 0.1.0-1 is a packaging "
            "decision about whether there is an upstream tarball, and this project has "
            "no releases. Issue #48."
            % (ver, "native" if native else "NOT native"))
    return ver


def check_pkgbuild(version):
    path = os.path.join(ARCH, "PKGBUILD")
    if not os.path.isfile(path):
        fail("arch/PKGBUILD", "%s does not exist." % path)
        return
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    m = re.search(r'^pkgver=\$\(sed -n \'(?P<sed>[^\']*)\'\s+"\$\{?_hdr\}?"\s*\)$',
                  text, re.M)
    if m is None:
        fail("arch/PKGBUILD pkgver",
             "pkgver is not written as a `sed` over the header. It may be correct by "
             "hand, but a hand-written pkgver is a version that has to be edited in "
             "two files on every bump and one of them will be missed -- which is "
             "exactly what happened to README's version number.")
        return
    # RUN IT, rather than reading it: the PKGBUILD's own comment says a BSD-vs-GNU
    # regex difference produces an EMPTY match, and makepkg turns an empty pkgver into
    # a malformed package rather than a refusal.
    cmd = m.group("sed").replace("\n", "")
    out = subprocess.run(["sed", "-n", cmd, os.path.join("..", "..", "src", "core",
                                                         "server.h")],
                         cwd=ARCH, capture_output=True, text=True)
    got = out.stdout.strip()
    if got == "":
        fail("arch/PKGBUILD pkgver",
             "the derivation produced an EMPTY string. On this platform (BSD sed) an "
             "empty result means a silently different regex, and makepkg would produce "
             "a malformed package rather than refusing. Command was: sed -n '%s'"
             % cmd)
        return
    if version is not None and got != version:
        fail("arch/PKGBUILD pkgver",
             "the derivation produced %s and src/core/server.h says %s." % (got, version))


def check_rules():
    """`make -n` with a stub `dh`, so the rules file's syntax and overrides are
    exercised without debhelper installed."""
    path = os.path.join(DEB, "rules")
    if not os.path.isfile(path):
        fail("debian/rules", "%s does not exist." % path)
        return
    with tempfile.TemporaryDirectory() as td:
        stub = os.path.join(td, "dh")
        with open(stub, "w", encoding="utf-8") as fh:
            fh.write("#!/bin/sh\necho \"dh $*\"\n")
        os.chmod(stub, 0o755)
        env = dict(os.environ)
        env["PATH"] = td + os.pathsep + env.get("PATH", "")
        for target in ("binary", "binary-arch", "build-arch", "clean", "check"):
            out = subprocess.run(["make", "-n", "-f", path, target],
                                 capture_output=True, text=True, env=env)
            if out.returncode != 0:
                fail("debian/rules",
                     "`make -n -f packaging/debian/rules %s` failed:\n%s"
                     % (target, (out.stdout + out.stderr).strip()[:400]))
                return
            if ("dh %s" % target) not in out.stdout:
                fail("debian/rules",
                     "target `%s` does not reach `dh %s`. The rules file is `dh $@` "
                     "with overrides, so every target should hand straight to dh -- a "
                     "target that does not is either misspelled or swallowed by a rule."
                     % (target, target))
                return
    # And the overrides the file declares must be overrides of targets dh HAS. The
    # list is the one debhelper 13 defines; a typo in an `override_` name is silently
    # ignored by dh, which is the failure this check exists for.
    known = {
        "override_dh_auto_configure", "override_dh_auto_build",
        "override_dh_auto_clean", "override_dh_auto_test",
        "override_dh_auto_install", "override_dh_auto_buildarch",
    }
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    for name in re.findall(r'^(override_\w+):', text, re.M):
        if name not in known:
            fail("debian/rules",
                 "`%s:` is not a target debhelper 13 defines. dh SILENTLY ignores an "
                 "`override_` for a target it does not have, so this line reads as "
                 "policy and does nothing." % name)


def check_control():
    path = os.path.join(DEB, "control")
    if not os.path.isfile(path):
        fail("debian/control", "%s does not exist." % path)
        return
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    for field in ("Source:", "Section:", "Maintainer:", "Build-Depends:"):
        if field not in text:
            fail("debian/control",
                 "no `%s` field. dpkg-buildpackage's error for a missing one names the "
                 "requirement rather than the file, and a packaging stub that has never "
                 "been read by the tool is exactly the state #48 was filed about." % field)
    if "debhelper-compat" not in text:
        fail("debian/control",
             "Build-Depends does not name `debhelper-compat`. Without it debhelper "
             "defaults to an old compat level, and without a `debian/compat` file "
             "(which is absent here) there is no other place the level is stated.")
    if not re.search(r'^Package:\s+\S', text, re.M):
        fail("debian/control", "no binary `Package:` stanza, so there is nothing to build.")


def check_install_rule():
    src = open(os.path.join(ROOT, "src", "CMakeLists.txt"), "r", encoding="utf-8",
               errors="replace").read()
    if "install(TARGETS irc-serve" not in src:
        fail("install rule",
             "src/CMakeLists.txt has no `install(TARGETS irc-serve ...)`. Every "
             "packaging path in this tree ends at `cmake --install`, so without it a "
             "successful Debian build produces a .deb containing no executable -- and "
             "the only way to find that out is to open the .deb.")
    if "RUNTIME DESTINATION bin" not in src:
        fail("install rule",
             "the irc-serve install rule does not name a `bin` destination. 6.2 says "
             "user programs go in /usr/bin, and dh_lint would flag it.")


def main():
    for d, what in ((DEB, "packaging/debian"), (ARCH, "packaging/arch")):
        if not os.path.isdir(d):
            sys.stderr.write("check-packaging: FAIL: %s does not exist, so every check "
                             "below would pass vacuously.\n" % what)
            return 1
    if not os.path.isfile(HEADER):
        sys.stderr.write("check-packaging: FAIL: src/core/server.h does not exist.\n")
        return 1

    version = header_version()
    check_changelog(version)
    check_pkgbuild(version)
    check_rules()
    check_control()
    check_install_rule()

    print("check-packaging: verified without Debian:")
    print("    src/core/server.h's IRC_SERVE_VERSION is the single definition and the")
    print("    Debian changelog and the Arch PKGBUILD both agree with it (the PKGBUILD")
    print("    by RUNNING its sed derivation, not by reading it).")
    print("    packaging/debian/changelog parses as a Debian changelog entry, its date")
    print("    parses as RFC 2822, and the date's WEEKDAY matches its day of month.")
    print("    packaging/debian/rules is valid make: every target reaches `dh <target>`")
    print("    under `make -n` with a stub dh, and every `override_` it declares is a")
    print("    target debhelper 13 actually defines.")
    print("    packaging/debian/control carries Source, Section, Maintainer, a")
    print("    debhelper-compat Build-Depends and a binary Package stanza.")
    print("    src/CMakeLists.txt installs TARGETS irc-serve to bin, which is the whole")
    print("    of 'the package contains the executable'.")
    if notes:
        print()
        print("check-packaging: NOT VERIFIABLE HERE, and reported rather than left to")
        print("an issue -- there is no dpkg-buildpackage, dpkg-source, dh or lintian on")
        print("this platform:")
        for n in notes:
            print("    * " + n)
    print()
    print("check-packaging: NOT CHECKED, AND NOT CLAIMED: whether a .deb can be")
    print("produced at all; whether dh_auto_configure's cmake flags are accepted; WHAT")
    print("THE PRODUCED .deb CONTAINS; ${shlibs:Depends} resolution (it needs")
    print("dpkg-shlibdeps and the built binary); and lintian, so Debian POLICY")
    print("compliance is unknown -- the absence of debian/copyright and of")
    print("debian/source/format are policy findings only lintian would report. Issue #48.")
    print("    A green run of this script is NOT a verified package. It is the part of")
    print("    the verification that can run on the machine where the work happens.")

    if failures:
        sys.stderr.write("check-packaging: FAIL: %d finding(s):\n" % len(failures))
        for what, why in failures:
            sys.stderr.write("    %s\n        %s\n" % (what, why))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())